### ISSUE TITLE
Using cellStyles

### ISSUE THREAD

**Issue by keishabien** [SheetJS/js-xlsx#1002]
I'm attempting to view the styling on my cells. I have whole rows that have a red background that need to be singled out. However, when I use cellStyles, I'm not seeing the 's' key in the cell object. Here's how my code is looking when reading the excel sheet. Data is the file, as I am using a file upload interface.

XLSX.read(data, {type: 'array',cellStyles: true}))

When viewing in the console, I'm not seeing the 's' field indicated that the styling will show there. I'm expecting a filled red background in 'A1'.

Thanks!
![screen shot 2018-02-19 at 5 09 57 pm](https://user-images.githubusercontent.com/18340388/36400646-d6fee170-1597-11e8-9117-c769c1a83a01.png)

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
