### ISSUE TITLE
Passing workbook to $scope in AngularJS

### ISSUE THREAD

**Issue by eugenevk** [SheetJS/js-xlsx#1007]
How can I pass the loaded workbook to the $scope? I want to do additional things with the workbook and actions but not immediately after you have selected the file.

**Comment by SheetJSDev** [comment]
This is a question better directed at an AngularJS support forum, but since the workbook is a plain JS object you should be able to assign it to `$scope.workbook`.  Based on [the directive from the angular demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/angular/SheetJS-angular.js#L51), the code probably looks something like:

```js
var SheetJSImportDirective = function() {
  return {
    scope: { opts: '=' },
    link: function ($scope, $elm, $attrs) {
      $elm.on('change', function (changeEvent) {
        var reader = new FileReader();

        reader.onload = function (e) {
          /* read workbook */
          var bstr = e.target.result;
          var wb = XLSX.read(bstr, {type:'binary'});

          /* update scope */
          $scope.$apply(function() {
            $scope.workbook = wb; // <-- pass workbook object to $scope
          });
        };

        reader.readAsBinaryString(changeEvent.target.files[0]);
      });
    }
  };
};

```
