### ISSUE TITLE
Headers style

### ISSUE THREAD

**Issue by ulknight** [SheetJS/js-xlsx#101]
Thank you. Your library very helpful. But I cannot find an example how to set "headers style". Could you please provide us with one? For example new background color and big font size.

PS Our project on node.js if it matters.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
