### ISSUE TITLE
formula cells not preserved in roundtrip if there's no value set

### ISSUE THREAD

**Issue by chinook25** [SheetJS/js-xlsx#1022]
When using XLSX format:

After saving a workbook with SheetJS, when attempting to then read the resulting file with SheetJS again, if a 'v' attribute is not set for formula cells, the cell is not read at all.

It would be great if SheetJS output was itself also completely and correctly read by SheetJS.

Test case (writing):
```
var workBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workBook, {}, 'Sheet');
workBook.Sheets.Sheet.A1 = {
  v: 'Test'
};
workBook.Sheets.Sheet.A2 = {
  f: 'A1'
};
workBook.Sheets.Sheet['!ref'] = 'A1:A2';
var workBookout = XLSX.write(workBook, {
  bookType: 'xlsx',
  type: 'array'
});
```

Now attempting to read in this file with SheetJS will only load the A1 cell (fileReader code omitted).
```
var workbook = XLSX.read(data, {
  type: 'binary'
});
```

**Comment by SheetJSDev** [comment]
This is far from obvious or ideal, but those are marked as stub cells.  You can set `sheetStubs:true` when reading the file to preserve:

```js
var workbook = XLSX.read(data, {
  sheetStubs: true,
  type: 'binary'
});
```

It's currently done this way because the formula itself gives no indication of the data types involved.

P.S.: since XLSX.read can accept an ArrayBuffer or Uint8Array, you can feed the output directly back into the parser.  Here's a complete fiddle: https://jsfiddle.net/z13zvs3k/

<details>
  <summary><b>Fiddle Code</b> (click to show)</summary>

```js
var wb1 = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb1, {}, 'Sheet');
wb1.Sheets.Sheet.A1 = {
  v: 'Test'
};
wb1.Sheets.Sheet.A2 = {
  f: 'A1'
};
wb1.Sheets.Sheet['!ref'] = 'A1:A2';
XLSX.writeFile(wb1, "issue1022.xlsx");
var data = XLSX.write(wb1, {
  bookType: 'xlsx',
  type: 'array'
});
var wb2 = XLSX.read(data, {
  sheetStubs: true,
  type: 'array'
});
console.log(wb2.Sheets.Sheet);
```

</details>

**Comment by chinook25** [comment]
Thank you, that works for us!
