### ISSUE TITLE
decrypt_agile is undefined

### ISSUE THREAD

**Issue by shenjo** [SheetJS/js-xlsx#1036]
0.12.5 xlsx.js 
When use this version lib to read password protected file
after debug and see this:
![image](https://user-images.githubusercontent.com/13912646/37450126-b57f769e-2867-11e8-99b5-1d69e21a6dd7.png)

thus I got "File is password-protected" error.
what does the variable come from?

**Comment by shenjo** [comment]
BTW , I searched in whole project and find nothing.

**Comment by SheetJSDev** [comment]
The `decrypt_agile` and `decrypt_std76` hooks are intentionally leaked so that our encryption module (part of the Pro compendium) can hook into the `read` and `readFile` functions (at a high level, Excel generates a plain unencrypted file then encrypts that file in a new package).   The checks are typeof-guarded so it shouldn't trigger an error in execution.
