### ISSUE TITLE
Excel Tables

### ISSUE THREAD

**Issue by jgranduel** [SheetJS/js-xlsx#1040]
Hi, 

I haven't found a way to get Excel Tables by name. Is this feature implemented, and if not, is it planned?
Thanks in advance

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
