### ISSUE TITLE
Format cells when creating xlsx - How to make the text center aligned ?

### ISSUE THREAD

**Issue by Pranamr** [SheetJS/js-xlsx#1050]
I am trying use "alignment"  cell style as shown below. But its not working
						B6: {
							"t": 's',
							"v": this.sapScript.veryhigh_effort,
							"s": {
								"alignment": {
									"horizontal": "center",
									"textRotation": 90
							}
						}}

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by ron2015schmitt** [comment]
Switching to [exceljs](https://github.com/exceljs) because of this.

**Comment by haskicbr** [comment]
Typical American dude created DLC for his project LOL

**Comment by DylanLyon** [comment]
The insanity of activity stripping out pre-existing styling from an imported sheet is complete lunacy. It isn't going to make me buy your premium edition, it's going to make me use a different package entirely.
