### ISSUE TITLE
How to copy styles during html table parsing?

### ISSUE THREAD

**Issue by Ost-max** [SheetJS/js-xlsx#1053]
There is an awesome method  table_to_book(data: any,  opts?: Table2SheetOpts): WorkBook;
However how can I copy some styles from html taple to xls table? 

For. ex: I need to make header of a table bold, and copy color of some cells. 

Thanks in advance.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by rohithb** [comment]
Check [linways/table-to-excel](https://github.com/linways/table-to-excel). 
Its a port of `table_to_book` but using [protobi/js-xlsx](https://github.com/protobi/js-xlsx).
It allows you to set basic styles like font color, size, alignment, cell color etc.
