### ISSUE TITLE
The element in the xlsx file cell is not displayed.

### ISSUE THREAD

**Issue by qingjiaowochengzd** [SheetJS/js-xlsx#1080]
hello,
If the content in the cell is displayed, it will be changed according to the width of the specified width. It is guaranteed that the width of the row after exporting excel does not need to be adjusted again. 
And Merge the cell, set the line background color.Can it be done?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
