### ISSUE TITLE
Excel a wrong row or column can be marked red, with a red background, can be positioned.

### ISSUE THREAD

**Issue by xcsweb** [SheetJS/js-xlsx#1082]
Excel a wrong row or column can be marked red, with a red background, can be positioned.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
