### ISSUE TITLE
Dropdown List for cell data options

### ISSUE THREAD

**Issue by amanthegreatone** [SheetJS/js-xlsx#1084]
Hi,

Is it possible to restrict a cell's data input to be a list of options? Something like [this](https://www.techrepublic.com/blog/microsoft-office/how-to-add-a-drop-down-list-to-an-excel-cell/).

**Comment by SheetJSDev** [comment]
Those are called "data validations".

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
