### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by elgalu** [SheetJS/js-xlsx#1089]
Is it possible to show an upload progress bar? for big files (up to 6GB).

**Comment by SheetJSDev** [comment]
https://sheet.js.org/ uses [spin.js](http://spin.js.org/) to show a spinner.  That demo uses a WebWorker to avoid blocking the browser UI.  The site starts the spinner just before passing off to the worker and turns it off just after receiving the result from the worker.

As for the general problem, the other formats have multiple steps that make a true "progress bar" difficult.  For example, XLSX and XLSB have to perform an unzip operation and XLS has to perform a CFB container expansion, but other formats like CSV and SYLK have no such step.  SYLK and QW1 can be organized in column-major order too, so reporting on a per-row basis is noisy.  And since some XLSX and XLS writers lie about the worksheet dimensions, the file has to be processed to know the progress.
