### ISSUE TITLE
Pivot configuration gets removed on reading and writing xlsx files

### ISSUE THREAD

**Issue by elliotpj** [SheetJS/js-xlsx#1093]
There is a xlsx file i am reading  which contains two sheets

I am appending data to the 1st Sheet named "Sheet1" and the second sheet ("Sheet2") contains a pivot related to "Sheet1", but when i write the file after appending the data on "Sheet1" on an new file , "Sheet2" just copies the data from the conrresponding readable sheet .

``` 

var XLSX = require('xlsx');

var fs = require('fs');

var data1= fs.readFileSync('./data1.xlsx','base64');

var wb = XLSX.read(data1, { type: "base64",raw:true});

var ws = wb.Sheets['Sheet1'];


XLSX.utils.sheet_add_json(ws, 
  [{Name:'Test X',Coverage:5000},{Name:'Test Y',Coverage:6000}], 
  {header: ["Name", "Coverage"], skipHeader: true,origin :-1});
  
var wopts = { bookType: 'xlsx',raw:true, type: 'base64', compression: true };
  
var data2 = XLSX.write(wb,wopts);

fs.writeFileSync('./data2.xlsx',data2,{encoding: 'base64'});
```

Is there anything i am missing ?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
