### ISSUE TITLE
Takes almost 1.30 min to read the xlsx sheet with 2 sheet max of 100 rows in 1st sheet and 5 rows in 2nd sheet

### ISSUE THREAD

**Issue by DevPrash** [SheetJS/js-xlsx#1094]
is there any way we can reduce the time.
xlsx file size =~10mb
code:

var form = new formidable.IncomingForm();
    form.parse(req, function(err, fields, files) {
        var f = files[Object.keys(files)[0]];
        //var workbook = XLSX.readFile(f.path);
        var buf = fs.read(f.path);
        var workbook = XLSX.read(buf, { type: 'array' });
        var first_sheet_name = workbook.SheetNames[0];
        var address_of_cell = 'A1';
        /* Get worksheet */
        var worksheet = workbook.Sheets[first_sheet_name];
        /* Find desired cell */
        var desired_cell = worksheet[address_of_cell];
        /* Get the value */
        var desired_value = (desired_cell ? desired_cell.v : undefined);
}

**Comment by SheetJSDev** [comment]
@DevPrash can you share the file?

**Comment by DevPrash** [comment]
[productExcel.xlsx](https://github.com/SheetJS/js-xlsx/files/1976883/productExcel.xlsx)

**Comment by SheetJSDev** [comment]
Since you're using nodejs, can you check the timing for the xlsx bin script?  To test, install xlsx globally with `npm install -g xlsx` (you may need to be a privileged user for this), then run `time xlsx productExcel.xlsx >/dev/null`.  Timing commands:

```bash
$ time xlsx productExcel.xlsx --read  ### read but do not convert
$ time xlsx productExcel.xlsx >/dev/null  ### convert first worksheet to CSV
$ time xlsx productExcel.xlsx -N 1 >/dev/null ### convert second sheet to CSV
```

Against node 10.0.0 on my computer it averages about 7 seconds for the first and third command and about 11 seconds for the second.

FWIW taking a look at the file, the first worksheet reports a range of `A1:D1048576` -- did you happen to do a fill-down of a formula?

**Comment by DevPrash** [comment]
Hi,
Thanks for your time.
I think its the issue of heap size. So i have increased the heap size and it started extracting the data faster.

**Comment by DevPrash** [comment]
So i am closing this issue.
