### ISSUE TITLE
cell format

### ISSUE THREAD

**Issue by yellowjian** [SheetJS/js-xlsx#1096]
how to format cell or row or column when export excel.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
