### ISSUE TITLE
Import Excel with Color Cells and Render in ag-grid

### ISSUE THREAD

**Issue by Han1989** [SheetJS/js-xlsx#1104]
I've an excel spread sheet (xlsx) with some data values and colors on it. My project need to import that excel sheet (exactly with all its cell background color and data) and show it in data grid (currently using ag-grid).

After I've done some research, I can get the styles of the Array by using 's' values. But 's' value is only available in worksheet object, and when i convert the worksheet into JSON by using "sheet_to_json", i couldn't get the 's' value anymore. 

Is there anyway to get that 's' value or, is there any suggestion to show that style into ag-grid?

sorry, I'm just just a beginner and question may be dumb.
Thank you.

![image](https://user-images.githubusercontent.com/2600180/39909308-cd9e38d4-5524-11e8-9200-9b0b15e65318.png)

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by saipandu9989** [comment]
can you share the code

**Comment by sureshbabu99** [comment]
how to uploaded data bind to grid. please share the sample code

**Comment by saipandu9989** [comment]
https://next.plnkr.co/edit/?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview
