### ISSUE TITLE
I set the cell text to bold, some text can not read the bold.

### ISSUE THREAD

**Issue by jenerse** [SheetJS/js-xlsx#1109]
In xlsx, I set the whole cell text to bold, not select part of the text in the cell. When I import this excel and output to html, the cell text is not bold, it is no font-weight, how can I fix this bug? or some solution?

Thanks a log.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
