### ISSUE TITLE
export html format with cell’s background color 

### ISSUE THREAD

**Issue by zhongchengsu** [SheetJS/js-xlsx#1111]
in function make_html_row(ws, r, R, o)，some code should be add
     if (cell.s != undefined && cell.s.fgColor != undefined && cell.s.fgColor.rgb != undefined)
           sp.style = "background-color:#" + 	cell.s.fgColor.rgb;

I have tested , some time the color can't show. I don't know why?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
