### ISSUE TITLE
Lost Pivot table formula

### ISSUE THREAD

**Issue by thiennhan2310** [SheetJS/js-xlsx#1112]
When I try to append new sheet to my current excel file which used pivot table. The new output file lost the pivot table format. 
I guess current version is not supported yet

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
