### ISSUE TITLE
Incorrect sheet range?

### ISSUE THREAD

**Issue by KevinBurton** [SheetJS/js-xlsx#1121]
I have a worksheet in my workbook that is reporting a range that is well beyond the range of data. I only have values for the first four columns and the first 3 rows but a call to 
`                                            var range = XLSX.utils.decode_range(workbook.Sheets[sheetName]['!ref']);`
is returning a range of 1000 rows and 4 columns. What is the criteria for calculating the range?

Thank you.

**Comment by SheetJSDev** [comment]
By default the self-reported file range is used.  This range may differ from the actual sheet range for a variety of reasons, sometimes an errant cell but oftentimes because of a third party export tool that cheated when calculating the range.  The wiki includes a [full scan to recalculate the range](https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions).
