### ISSUE TITLE
Newbie - js-xlsx - Open, read, write into one cell and save onto the same file (not a new one!)

### ISSUE THREAD

**Issue by yipiha** [SheetJS/js-xlsx#1124]
Hi,

Nothing fancy here I hope. 

Each row of my Excel file contains parameters for an API so I just want to open up the file, loop through 4 lines skipping the header. For each row, I get values in columns "A, B, C" and use these information to call an API.

Now I just want to add to the file and on the same line the result of the call.

So if line 6 had the values: 1, 2, 3 in columns A, B and C
And the result of calling the API was 4
I want the final line 6 to be: 1, 2, 3, 4

I don't understand: how to write to a single cell and how to save **that** excel file?
All examples show how to export or save to another file but this is not what I want.

Could someone please help me? Thanks in advance!

**Comment by SheetJSDev** [comment]
The docs are mostly devoted to the in-memory model (the "common spreadsheet format").  Importing a file generates an object according to that model, and the model can be exported to file.  To change a file, import the file then manipulate the model and save.

https://jsfiddle.net/sheetjs/zcfs28rL/ is an example that reads a file, changes cell A1 to the text "issue1124", and exports the file:

```js
function process_wb(wb) {
  /* get the first worksheet */
  var ws = wb.Sheets[wb.SheetNames[0]];

  /* change A1 to the label "issue1124" */
  if(!ws["A1"]) ws["A1"] = {};
  ws["A1"].t = "s";
  ws["A1"].v = "issue1124";

  /* save file */
  XLSX.writeFile(wb, "issue1124.xlsx");
}
```

**Comment by macasas** [comment]
I am pleased to have found this example, because I am using this exact code in a node example but it is not working as expected.

I have 3 different XLSX template files that I use to read in.

Each workbook has a Master worksheet where the only information is 
A2=Country
A3=Language

I am reading in each of the 3 template files and writing to B2 and B3, the name of the country and the language.

Even though the workbook shows all the changes have been made in all 3 cases, when it comes to the XLSX.writeFile line, only workbooks that had some text in B2, or B2 and B3, before the file was read, save the new content.  

If A2 and A3 are the only content before reading, even if the workbook shows B2 and B3 with new content in the model, writeFile does not save this information.

**Comment by SheetJSDev** [comment]
If the new cell is outside the existing worksheet range, it won't be written to the file.  To update it, there's an example function `add_to_sheet` in the wiki https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions#adding-a-cell-to-a-range

```js
add_to_sheet(ws, "A1"); // second argument is the cell address
```

**Comment by macasas** [comment]
That did it for me, thanks for a fast response.

I added the 2 functions and then called it from here

```
if(!ws["A1"]) {
  ws["A1"] = {};
  add_to_sheet(ws, "A1");
}
ws["A1"].t = "s";
ws["A1"].v = "issue1124";
```

**Comment by rkrkrediffmail** [comment]
@macasas thanks for the code. but i am getting an error **Uncaught ReferenceError: add_to_sheet is not defined** refer this filddle https://jsfiddle.net/kyx749dg/ . could you kindly have a look and suggest why its not working? PS :  I am not using node.
