### ISSUE TITLE
How to output a fullwidth space?

### ISSUE THREAD

**Issue by Sakura777** [SheetJS/js-xlsx#1156]
Thank you for a nice script.
I use Japanese. When this code is executed, the fullwidth space (Ideographic space) in the exported file disappears.

```
//in HTML
<td>　abc</td>

//in JS
var wb = XLSX.utils.book_new();
var ws = XLSX.utils.table_to_sheet(document.getElementById(table));
XLSX.utils.book_append_sheet(wb, ws, "sheetname");

//in exported Excel
|abc|
(I want to |　abc|)
```
What should I do? Do I need to set something?

**Comment by SheetJSDev** [comment]
Good catch!  IDEOGRAPHIC SPACE U+3000 is a whitespace character according to JS but not according to DOM rules.  The [whitespace normalization](https://github.com/SheetJS/js-xlsx/blob/master/bits/22_xmlutils.js#L177) should be restricted to the DOM whitespace characters `/[\t\n\r ]+/` instead of the full whitespace class `\s+`. 

IF you would like to submit a PR, the linked line should be corrected to use the restricted class `[\t\n\r ]+`

**Comment by Sakura777** [comment]
Thank you for the advice!
I rewrote the following code and it went well :)

```
//htmldecode function

//before
var o = str.trim().replace(/\s+/g, " ").replace(/<\s*[bB][rR]\s*\/?>/g,"\n").replace(/<[^>]*>/g,"");

//after : Deleted trim() and replaced " " with "　"
var o = str.replace(/\s+/g, "　").replace(/<\s*[bB][rR]\s*\/?>/g,"\n").replace(/<[^>]*>/g,"");
```
