### ISSUE TITLE
csv fixed length between delimiter

### ISSUE THREAD

**Issue by mohamed-hendawy** [SheetJS/js-xlsx#1161]
i want to add fixed length between delimiters when exporting like this : 

hello &nbsp; &nbsp;| &nbsp; &nbsp;every| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;one|
some &nbsp; |  &nbsp;&nbsp; &nbsp;thing| &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;hereeeee|
bla  &nbsp;&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp; &nbsp; &nbsp;bla|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;bla|

**Comment by SheetJSDev** [comment]
If you don't need the actual delimiter character, the PRN output type lines up the columns:

```js
var i = "hello,every,one\nsome,thing,hereeeee\nbla,bla,bla";
var wb = XLSX.read(i, {type:"binary"});
var prn = XLSX.write(wb, {bookType:"prn", type:"string", sheet:"Sheet1"});
```

And the output looks like:

```
hello      every     one       
some       thing     hereeeee  
bla        bla       bla       
```

For more advanced work, you could write a JS function to post-process the DSV output.  After using `sheet_to_csv` to convert with the option `FS:"|"`, you can manually split and walk the array of arrays:

```js
var dsv = XLSX.utils.sheet_to_csv(wb.Sheets.Sheet1, {FS:"|"});
var arr = dsv.split("\n").filter(r => r).map(r => r.split("|"));
var C = Math.max.apply([], arr.map(r => r.length));
for(var i = 0; i < C; ++i) {
  var w = Math.max.apply([], arr.map(r => (r[i]||"").length));
  for(var R = 0; R < arr.length; ++R) arr[R][i] = (arr[R][i]||"").padEnd(w+1, " ");
}
var out = arr.map(r => r.join("|")).join("\n");
```

which will look like:

```
hello |every |one      
some  |thing |hereeeee 
bla   |bla   |bla      
```

(to right-align, use `padStart` rather than `padEnd`)
