### ISSUE TITLE
Roundtripping doesn't preserve formatted text

### ISSUE THREAD

**Issue by KingJT** [SheetJS/js-xlsx#117]
Repeat the process described in https://github.com/tealeg/xlsx/issues/45#issuecomment-56096421 and use the `xlsx` command to open and save the XLSX.  The new file loses the original formatting

**Comment by gabmontes** [comment]
@m1sta what package did you found that supports roundtripping?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
