### ISSUE TITLE
merged cell text align parse from excel not work

### ISSUE THREAD

**Issue by nvcken** [SheetJS/js-xlsx#120]
I have a excel file with have some text align center on merged cell.
I readFile to workbook then writeFile from that workbook , finally I open new output file I see that text align left on merged cell not center as original

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
