### ISSUE TITLE
How to get first 5 rows of each sheet?

### ISSUE THREAD

**Issue by sreepurnajasti** [SheetJS/js-xlsx#1225]
how can I get first 5 rows of a sheet? Right now I am using the following code which gives me whole file content in arrays. 
```
 let workbook = xlsx.readFile(path)
 let sheetsList = workbook.SheetNames
 let sheetData = xlsx.utils.sheet_to_json(workbook.Sheets[sheetsList[i]], {
      header: 1,
      defval: '',
      blankrows: true
 });.
```
Thanks in advance.

**Comment by SheetJSDev** [comment]
The `readFile` function takes an options argument.  Using the `sheetRows` option 
https://docs.sheetjs.com/#parsing-options , the code would be

```js
let workbook = xlsx.readFile(path, {sheetRows: 5});
```

**Comment by sreepurnajasti** [comment]
@SheetJSDev Thanks!!

**Comment by 0APOCALYPSE0** [comment]
Hi, I have one issue here. So for example if the file size is too large like around 500mb or more and I just want to read only like top 5 or 10 lines then in this case I can use sheetRows property with read method but before that I will read.xlsx file using FileReader as arrayBuffer but because the file size is too large it crashing my browser or take more than 30 minutes so how can i handle this issue. If i am trying to slice .xlsx file using slice method of blob then it is causing this error while reading Error: Corrupted zip : can't find end of central directory

**Comment by rohit-singh-vmart** [comment]
@SheetJSDev This `readFile` function works fine for small-size files (30MB & row 100000) but it is taking more time on large files ( 150 MB, around 1.5 min). Is it because it is reading the whole data first and then selecting the first selected `sheetRows`?
What could be the reason for the inefficiency of this function for larger files?

**Comment by Rohit-singh19** [comment]
@SheetJSDev  This `readFile` function works fine for small-size files (30MB & row 100000) but it is taking more time on large files (150 MB, around 1.5 min). Is it because it is reading the whole data first and then selecting the first selected `sheetRows`?
What could be the reason for the inefficiency of this function for larger files?
Regardless of the file's size, how can I read only the first selected `sheetRows` rows?

Thanks in advance.
