### ISSUE TITLE
Returning wrong sheet if the workbook contains a very hidden sheet

### ISSUE THREAD

**Issue by rla-dev** [SheetJS/js-xlsx#123]
We are processing .xlsx files generated by SAP which contain sheets marked as 'xlsSheetVeryHidden'. In that case, accessing a visible sheet by name returns the content of the non-visible sheet (which even has a different name). It seems that the index of a sheet is calculated based on the list of 'visible' and 'normally hidden' sheets instead of all available sheets.

This behavior can easily been verified on a simple workbook containing two sheets in which the first had been marked as 'very hidden' in the 'View Code' window. 

![veryhidden](https://cloud.githubusercontent.com/assets/8556384/4460463/9e5072d6-48b2-11e4-813e-0c94e702be97.png)

**Comment by Mior** [comment]
This seems to be still an issue.
I have prepared fix so that in Sheets property are all available sheets but in SheetNames are only visible tabs.
Users could iterate trough Sheets to get all sheets or base on SheetNames for only visible once.

It may be kind a confusing to the user that in SheetNames are not all sheets, only visible but in the other hand what if he want to display only visible sheets.
We probably need some property `type` but what could be values for that? Is there any such sheet type in specification for our purpose? 

@SheetJSDev I can see 36 Pull requests pending, is it even worth contributing? This project is one of few with xls/xlsx js projects and I love to see it live.

**Comment by JohnBicknell** [comment]
@Mior Thanks! this lost issue lost me the best part of a day, just tried out your fix and works great.

**Comment by darrinholst** [comment]
Please consider pulling in @Mior's pr. It solved my problem that I lost a few hours on today.

**Comment by SheetJSDev** [comment]
We're going in the opposite direction: including very hidden sheets in the list.  This also lets us put in chartsheets and other features.
