### ISSUE TITLE
Reading a xlsx file properly without any error which can't be opened by MS-Excel. This issue was not there with version 0.8.8

### ISSUE THREAD

**Issue by reachmehere89** [SheetJS/js-xlsx#1236]

**Comment by SheetJSDev** [comment]
Do you have an example file?

**Comment by reachmehere89** [comment]
How can I upload that sample file here?

**Comment by reachmehere89** [comment]
Yes that is what I mentioned. In version 0.8.8 this throws an error but latest version is successfully reading it

**Comment by SheetJSDev** [comment]
The root of the problem is that Excel actually behaves differently based on the file extension.  If you change the file extension to XLS or CSV, Excel actually will read the file and interpret it as a one-line file.  So this is more or less intended behavior now that the library supports more plaintext file formats.

**Comment by reachmehere89** [comment]
So is there a way we can force reading the file in XLSX format only using this library?
