### ISSUE TITLE
Require assistance, Code doesnt seem to work

### ISSUE THREAD

**Issue by CasualRocket** [SheetJS/js-xlsx#1274]
I am trying to get this working for a project i have for a restricted network. User creates an excel with 1500 items on it, i need that to become a HTML table so i can transfer it to a SharePoint list. The issue is i cannot get your code to work on Fiddle to even begin to move it the isolated network. Not to mention i cannot bring the xlsx.min.js file over due to all the special characters. 

JSfidd: https://jsfiddle.net/xpvt214o/819660/

**Comment by SheetJSDev** [comment]
You can check the developer tools to see the errors.

In this case, it's because web workers were enabled but the worker scripts could not be found.  Uncheck the "Use Web Workers" box.

Additionally, if you are doing this in the web browser, there are bundled files in the dist directory.  Use https://unpkg.com/xlsx/dist/xlsx.full.min.js

**Comment by CasualRocket** [comment]
I think i fixed it by removing huge chunks of the code.

"You can check the developer tools to see the errors." i linked the JSfiddle with the assumption you would

"Ke" is not a constructor
