### ISSUE TITLE
Critical issue: Browser hanging when converting some xlsx file to json

### ISSUE THREAD

**Issue by sreenivas369** [SheetJS/js-xlsx#1363]
we are converting below xlsx file to json in chrome browser
(https://s3-ap-southeast-1.amazonaws.com/learnyst-wordimport-issues/QuestionsImportTemplate-v3.xlsx)

when converting xlsx to json, js-xlsx library is going to infinite loop and browser CPU usage 100%

iam using below code for converting

```
reader.onload = function(e) {
  var arrayBuffer = e.target.result;
  var data = new Uint8Array(arrayBuffer);
  var workbook;
  try{
    workbook = XLSX.read(data, {
      type: 'array'
    });
  }catch(err){
    window.alert(err);
    return;
  }
    /* DO SOMETHING WITH workbook HERE */
    var first_sheet_name = workbook.SheetNames[0];
    /* Get worksheet */
    var worksheet = workbook.Sheets[first_sheet_name];
    var sectionArray = XLSX.utils.sheet_to_json(worksheet,{raw:true});
  };

  reader.onerror = function(ex) {
    console.log(ex);
};
reader.readAsArrayBuffer(this.file);
```

I tried this xlsx with the hosted live demo(https://oss.sheetjs.com/js-xlsx/). Live demo also has same issue

Please help to resolve

**Comment by reviewher** [comment]
The range is extremely large:

```xml
  <dimension ref="A1:AML1048576"/>
```

There's apparently something specified in the last row:

```xml
    <row r="1048576" spans="6:6" x14ac:dyDescent="0.25">
      <c r="F1048576" s="6"/>
    </row>
```

So the complete degradation comes from the library thinking there are 1048576 rows when there's only a stub in that last row.

Attached you will find an updated file with the errant row 1048576 and cell F1048576 removed:

[QuestionsImportTemplate-v3.xlsx](https://github.com/SheetJS/js-xlsx/files/2599261/QuestionsImportTemplate-v3.xlsx)

**Comment by sreenivas369** [comment]
Ok Thanks. We will try to use the range method to solve this issue

**Comment by ferdymercury** [comment]
I just had the same issue. The problem happens when I open one particular XLSX file in libreoffice, and then edit something and save it again as XLSX. It automatically sets the dimension to A2:M1048576
I did a "grep" on the xml files and I do not see anything on M1048576
If I open with libreoffice and type CTRL+END, then it goes to M100, not M1048576, so not sure where the issue comes from.
I solved it by editing by hand the range in the XML file.

Edit: well, I did find something on row 1048576, the M was coming from the horizontal limit.
`<row r="1048576" customFormat="false" ht="12.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false"></row>`
Removing that line from the XML solved the issue when resaving also, and the resulting range was automatically cropped to M100.
It's weird, because I had tried before deleting that row completely directly from the Excel file. It only works if I delete it by hand from the XML file with a text editor.
