### ISSUE TITLE
Reading file from URL using fs getting limit error

### ISSUE THREAD

**Issue by iamsandeepgupta** [SheetJS/js-xlsx#1377]
I am getting file from a static path and reading the file using fs. I am getting byte array and when i am sending that byte array to XLSX.read(), it is generating exception as "End of data reached (data length = 5268166, asked index = 5664051). Corrupted zip ?". File is newly created. Please tell how can i read this.
When i am sending data in form on binary string from UI then every things is working as per it. But when i sending through server then it is generating the exception.

**Comment by SheetJSDev** [comment]
Something in your application is interpreting as UTF-8 string instead of binary string.  Compressed ZIP files may contain byte sequences that are not valid when interpreted as UTF-8, and some body parsers and libraries may proactively parse incorrectly.

If you are using nodejs, `fs.readFileSync(path, {encoding: "binary"})` will give you a binary string.  Alternatively, you can just pass a buffer through the app and avoid the problem.
