### ISSUE TITLE
How to format while writing xlsx to file ?

### ISSUE THREAD

**Issue by ashu-daffodil** [SheetJS/js-xlsx#146]
Hi
I'm using this module and it works perfect for most of my requirements. The only exception is that it trims all of the leading space values. I want these spaces to be there as they are in the input and avoid trim functionality.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
