### ISSUE TITLE
existing sheets style modified

### ISSUE THREAD

**Issue by himakumar** [SheetJS/js-xlsx#150]
Hi,

I tried to modify existing excel file, that has two sheet and one sheet I need modify, don't want to modify another sheet.
I created a workbook with readfile and passed that to write function to write data into 1st sheet and this write also modified the second sheet graphs.
is there any way to fix it?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
