### ISSUE TITLE
Concatenation is not working with '&'

### ISSUE THREAD

**Issue by VSelemanov** [SheetJS/js-xlsx#1514]
Hi.
I have a problem with column concatenation.
It's not working with '&'; Example: =A2&","&B2
But it working with standart function CONCAT; Example: =CONCAT(A2&","&B2)
Result of these formulas is equal in MS Excel / LibreOffice Calc, but after parsing by xlsx library result of first example is "0" and result of second example is concatinated columns values

**Comment by SheetJSDev** [comment]
@VSelemanov can you share the file that is not being read properly by sheetjs?  likely the file did not store the correct results when it was saved

**Comment by VSelemanov** [comment]
@SheetJSDev test file: https://drive.google.com/open?id=15OPP4LE9Xi9QtzWPZ8U2rkvSlk-ubNlN
I want to get value of FacilitryIDPick column.
In first row of data library returns calculated value from column after parsing.
In second row of data library returns "0" after parsing.

**Comment by VSelemanov** [comment]
@SheetJSDev I think that this is problem with cell types when I try to parse file.
When I copy the CONCAT formula to bellow cells, the problem of this issue returns.
If I input CONCAT formula manualy - cell type is t: "s", if I copy CONCAT formula - cell type is t: "n"

**Comment by VSelemanov** [comment]
@SheetJSDev I think that I found the problem: when I try to parse .xls file - problem is staying, but if I try to parse .xlsx file - problem solved

**Comment by SheetJSDev** [comment]
This is an error in the tool that wrote the file.  To be clear, the record for that file is of type [Formula](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/8e3c6978-6c9f-4915-a826-07613204b244) and has the following payload:

```
01 00 0a 00 34 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 17 00 23 46 00 00 00 24 01 00 00 c0 17 01 00 2c 24 01 00 03 c0 42 04 ff 00
```

Breaking it down: the address is "K2" and the formula value is

```
00 00 00 00 00 00 00 00
```

To interpret that, see the docs for type [FormulaValue](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/39a0757a-c7bb-4e85-b144-3e7837b059d7)

The last two bytes are 0x0000.  Since they are not `0xFFFF`, the whole thing is interpreted as a 64 bit floating point number whose value is `new Float64Array(new Uint8Array(Array.from({length:8}, ()=>0)).buffer)[0] == 0`

--

In any case, this has been reported to LO https://bugs.documentfoundation.org/show_bug.cgi?id=125466 and that's about as far as we can go.
