### ISSUE TITLE
i want to change the download path or the directory.. but how??? can anybody help me?? plsss 🙏🙏🙏

### ISSUE THREAD

**Issue by ShubhamProgrammer** [SheetJS/js-xlsx#1524]
i want to change the download path or the directory.. but how??? can anybody help me?? plsss 🙏🙏🙏

_Originally posted by @votyox69 in https://github.com/SheetJS/js-xlsx/issues/817#issuecomment-477935692_

**Comment by SheetJSDev** [comment]
The library ultimately falls back on various browser APIs that can force a download.  Most of them do not let you programmatically control where the file will be stored.  The naive approach of using slashes doesn't work since some browsers will convert to underscores when saving.  Until Chrome comes up with a solution, it's out of our hands :(
