### ISSUE TITLE
Trying to remove whitespace from a column header

### ISSUE THREAD

**Issue by Rach81** [SheetJS/js-xlsx#1529]
This is really two questions in one. Hopefully someone can help me...

I have a lambda function written in node.js which uses the library to convert an excel spreadsheet into JSON. This was working fine except for that some of the column headers had whitespace at the end. I was trying to remove it by adding the code below (in visual studio code), which I found in another issue.

https://github.com/SheetJS/js-xlsx/issues/443#event-1012916154

```
 var range = XLSX.utils.decode_range(ws['!ref']);
    for(var R = range.s.r; R <= range.e.r; ++R){
      for(var C = range.s.c; C <= range.e.c; ++C) {
        var coord = XLSX.utils.encode_cell({r:R, c:C}), cell = ws[coord];
        if(!cell || !cell.v) continue;
        // clean up raw value of string cells
        if(cell.t == 's') cell.v = cell.v.trim();
        // clean up formatted text
        if(cell.w) cell.w = cell.w.trim();
      }
    }

```
Instead of removing white space it removed the entire column. When I reverse these changes the column was still missing when I ran the previously working code.

1. Does anyone know why column is still missing when I have reverted to the original code?
2. How can I trim just the white space from a column header with this library?

**Comment by MelvinVermeer** [comment]
We also wanted to trim headers, this is what we used.
Lodash - mapKeys ([docs](https://lodash.com/docs/4.17.15#mapKeys))
Hope this helps.

```javascript
const json = XLSX.utils
        .sheet_to_json(workbook.Sheets['Sheet1'])	        
        .map(row => mapKeys(row, (value, key) => key.trim()))
```

**Comment by SheetJSDev** [comment]
If a column is missing, likely the header label is missing or the range is incorrect.

To trim column headers:

```js
function trim_headers(ws) {
	if(!ws || !ws["!ref"]) return;
	var ref = XLSX.utils.decode_range(ws["!ref"]);
	for(var C = ref.s.c; C <= ref.e.c; ++C) {
		var cell = ws[XLSX.utils.encode_cell({r:ref.s.r, c:C})];
		if(cell.t == "s") {
			cell.v = cell.v.trim();
			if(cell.w) cell.w = cell.w.trim();
		}
	}
}
```

**Comment by zoozalp** [comment]
I'm getting extra spaced on the left and right side of header name when the column is is currency format. Below is the workaround I'm using for now. It works fine for small file but may need a faster solution for larger files.

```
import xlsx from "xlsx";

export function ReadExcelFile(filename, sheetname) {
  const workbook = xlsx.readFile(filename);
  const sheet = workbook.Sheets[sheetname || workbook.SheetNames[0]];
  return xlsx.utils.sheet_to_json(sheet).map(row =>
    Object.keys(row).reduce((obj, key) => {
      obj[key.trim()] = row[key];
      return obj;
    }, {})
  );
}
```

**Comment by tahaerden** [comment]
> If a column is missing, likely the header label is missing or the range is incorrect.
> 
> To trim column headers:
> 
> ```js
> function trim_headers(ws) {
> 	if(!ws || !ws["!ref"]) return;
> 	var ref = XLSX.utils.decode_range(ws["!ref"]);
> 	for(var C = ref.s.c; C <= ref.e.c; ++C) {
> 		var cell = ws[XLSX.utils.encode_cell({r:ref.s.r, c:C})];
> 		if(cell.t == "s") {
> 			cell.v = cell.v.trim();
> 			if(cell.w) cell.w = cell.w.trim();
> 		}
> 	}
> }
> ```

@SheetJSDev can you explain how this function works since it is quite hard to read? Also does it only loop through the header (1st) row?

I believe encoding the header row first, then generating the JSON object is a much better idea then @zoozalp 's solution which loops through all the objects (can be thousands) and re-creating each object with trimmed keys.

**Comment by SheetJSDev** [comment]
In retrospect the information is scattered in the README.  If this explanation makes sense, please let us know how the README can be improved.

the `!ref` key of the worksheet object is a string that encodes the range (A1-style, like "A1:D20").

`XLSX.utils.decode_range` parses that into an object like `{ s: {r: 0, c:0}, e: {r:19, c:3} }` where `s` holds the upper-left address and `e` holds the lower-right address.

It loops the columns of the worksheet.  For each column, it tries to find the corresponding cell in the header row.  Since cells are addressed by A1-style strings (e.g. `ws["B2"]`), it generates the string using `XLSX.utils.encode_cell`.  If the cell exists and is a string cell (`cell.t == "s"`), then it will trim the string value (`v` property) and the formatted string property (`w` property).
