### ISSUE TITLE
Read multiple Excel workbooks in parallel?

### ISSUE THREAD

**Issue by dauledk** [SheetJS/js-xlsx#1618]
Is it possible to read multiple excel sheets in parallel?

**Comment by SheetJSDev** [comment]
JS does not provide for any sort of parallelism (it is "single-threaded").  Any concurrency must be supplied by the host environment, so the technical answer is "it depends on where you are running it".  ExtendScript for example doesn't really provide a concurrency primitive.

Common techniques include web workers in the browser and child processes on the server side, and there are various demos showing those use cases.  For example, the demo https://oss.sheetjs.com/js-xlsx/ can use web workers (view-source to see how it works).  Consult the nodejs docs or browser WebWorker spec.

**Comment by dauledk** [comment]
I used Nodejs Worker Threads to do this, and it worked really well. I just leave a link to the documentation [here](https://nodejs.org/api/worker_threads.html).

**Comment by ravithejappl** [comment]
@alexbjorlig  why don't you write a sample code here which uses worker threads, it will be useful for many people.

**Comment by alexbjorlig** [comment]
Good point. The code was actually written for a client, let me just find it when I get to the computer

**Comment by SheetJSDev** [comment]
The example in https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads was clearly designed with xlsx in mind.  4 line change from the doc example:

```js
const {
  Worker, isMainThread, parentPort, workerData
} = require('worker_threads');

if (isMainThread) {
  module.exports = function parseXLSXAsync(buffer) {
    return new Promise((resolve, reject) => {
      const worker = new Worker(__filename, {
        workerData: buffer
      });
      worker.on('message', resolve);
      worker.on('error', reject);
      worker.on('exit', (code) => {
        if (code !== 0)
          reject(new Error(`Worker stopped with exit code ${code}`));
      });
    });
  };
} else {
  const { parse } = require('xlsx');
  const buffer = workerData;
  const wb = XLSX.read(workerData, {type: "buffer"});
  const result = XLSX.utils.sheet_to_csv(wb.Sheets[wb.SheetNames[0]]);
  parentPort.postMessage(result);
}
```

**Comment by ravithejappl** [comment]
Fab! 🙏

**Comment by ravithejappl** [comment]
@alexbjorlig  what's wrong with mycode?

**Comment by alexbjorlig** [comment]
Hi @ravithejappl - I would never laugh. We are all here to help each other ☺️

The code you provided is not bad, but maybe it does not do what you actually expect it to do. The video I watched that finally made me understand how node works is [this one](https://www.youtube.com/watch?v=8aGhZQkoFbQ). It explains in a very good way what async code actually is.

The `xlsx` library is blocking, so it does not become truly async, when you wrap it in a promise (hopefully watching the video will explain this better, otherwise let me know).

In other words, if you should read 2 excel workbooks, and each operation took 2 minutes the following 2 operations would take the same time:

```typescript
await readExcel('workbook1');
await readExcel('workbook2');
console.log('done') // <== executes after 4 minutes, with 1 thread

await Promise.all([
  readExcel('workbook1'),
  readExcel('workbook2')
]);
console.log('done') // <== Also executes after 4 minutes, with 1 thread

```

So what you actually need is a new instance of nodejs, processing each workbook. This can be obtained with worker threads, so you get something like:

```typescript
await Promise.all([
  readExcelWrappedWithWorker('workbook1'),
  readExcelWrappedWithWorker('workbook2'),
])
console.log('done'); // <== Executes after 2 minutes, with 2 threads
```

@ravithejappl I hope this is help enough, otherwise let me know. If you need more help, then you could maybe create a small public repo, where I can help you debug any problems that you encounter. Now back to todays work 😅

**Comment by ravithejappl** [comment]
Thanks! Understood.
