### ISSUE TITLE
How to get image data from cell ?

### ISSUE THREAD

**Issue by Nishchit14** [SheetJS/js-xlsx#205]
I have a excel with every row containing a single image in cell.

Now i want to store this image folder but i cant get any data with this cell.

Plz inform me if this is possible to get image (base64/other) from excel cell.

__ND

**Comment by meikidd** [comment]
+1

**Comment by yanCode** [comment]
now i am having similar requirements in my present project...

**Comment by nitishmittal1990** [comment]
+1

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
