### ISSUE TITLE
Possible to skip first n rows when parsing?

### ISSUE THREAD

**Issue by nottinhill** [SheetJS/js-xlsx#215]
Hi, is it possible to skip the first n rows when parsing, I am parsing like this (in coffee)

```
sheet: (@file) ->
  filename          = 'uploads/' + @file
  workbook          = J.readFile(filename)
  workbookJSON      = J.utils.to_json(workbook)
  workbookProps     = J.readFile(filename, {bookProps:true})
  sheetname         = workbookProps[1].SheetNames[0]

  sheetArray        = []
  for k,v of workbookJSON
      sheetArray.push k

  sheetone = sheetArray[0]
  sheetoneJSON      = workbookJSON[sheetone]
  return sheetoneJSON

  slicedSheet.forEach (item) ->
      # do stuff
```

**Comment by SheetJSDev** [comment]
@nottinhill There's no option at the moment to skip the first `n` rows.  There are a few easy ways to work with the existing utilities:

A) If you using standard utility functions, you can change the worksheet `!ref` property to restrict to a subset of the worksheet:

```
/* get the range */
var range = J.utils.decode_range(worksheet['!ref']);
/* skip n rows */
range.s.r+= n;
if(range.s.r >= range.e.r) range.s.r = range.e.r;
/* update range */
worksheet['!ref'] = J.utils.encode_range(range);
```

B) You can directly slice the output of `to_json` (since it's a normal array):

```
function get_json_sliced(filename, rows) {
    rows = rows || 0;
    var wb = J.readFile(filename);
    var sheetnames = wb[1].SheetNames;
    var json = J.utils.to_json(wb);
    sheetnames.forEach(function(sheetname) {
        if(Array.isArray(json[sheetname])) json[sheetname] = json[sheetname].slice(rows)
    });
    return json;
}
```

The difference between the two approaches is that the latter will still interpret the first row as a header row, whereas the former will completely ignore the fact that the previous rows exist.

**Comment by keyscores** [comment]
@SheetJSDev Where is decode_range documented? It would be nice to add this example to the github docs.

**Comment by keyscores** [comment]
Correction, I was using a previous version of SheetJS, I don't get the same error. Still would be nice to have this util documented in the sheetjs docs

**Comment by SheetJSDev** [comment]
Even though it could be cleaned up a bit,  https://github.com/SheetJS/js-xlsx#json covers how to control the range of the JSON output.
