### ISSUE TITLE
[Question] Always read cell content as strings

### ISSUE THREAD

**Issue by HugoCornu** [SheetJS/js-xlsx#230]
Hi JS-XLSX team and community,

I am using readFile and sheet_to_json to look into user generated worksheets.
I would like to always read the content of a cell as a string.

This is not the case by default, because if a cell contains for exemple a number, it will return a javascript number object.
This behavior is awesome in general case but in my case, I would really prefer strings.

How do I this? (I tried "cellNF: true" and "format_cell" but without fully understanding the doc)

Thanks

**Comment by SheetJSDev** [comment]
@HugoCornu the default behavior of sheet_to_json is to always return strings.  Consider the RkNumber test file https://github.com/SheetJS/test_files/blob/master/RkNumber.xlsx which has numbers in the sample column:

```
> var XLSX = require('xlsx')
> var wb = XLSX.readFile('RkNumber.xlsx')
> var json = JSON.stringify(XLSX.utils.sheet_to_json(wb.Sheets.RkNumber))
> json
'[{"fX100":"0","fInt":"0","sample":"10000000"},{"fX100":"0","fInt":"1","sample":"1200455"},{"fX100":"1","fInt":"0","sample":"0.01"},{"fX100":"1","fInt":"1","sample":"12004.55"}]'
> JSON.parse(json)
[ { fX100: '0',
    fInt: '0',
    sample: '10000000' },
  { fX100: '0',
    fInt: '1',
    sample: '1200455' },
  { fX100: '1',
    fInt: '0',
    sample: '0.01' },
  { fX100: '1',
    fInt: '1',
    sample: '12004.55' } ]
```

To return numbers, pass an options argument to sheet_to_json with raw set to true:  
```
> var jsonraw = JSON.stringify(XLSX.utils.sheet_to_json(wb.Sheets.RkNumber, {raw:true}))
> jsonraw
'[{"fX100":"0","fInt":"0","sample":10000000},{"fX100":"0","fInt":"1","sample":1200455},{"fX100":"1","fInt":"0","sample":0.01},{"fX100":"1","fInt":"1","sample":12004.55}]'
> JSON.parse(jsonraw)
[ { fX100: '0',
    fInt: '0',
    sample: 10000000 },
  { fX100: '0',
    fInt: '1',
    sample: 1200455 },
  { fX100: '1',
    fInt: '0',
    sample: 0.01 },
  { fX100: '1',
    fInt: '1',
    sample: 12004.55 } ]
```

In this example, the original file was saved with the fX100 and fInt columns stored as strings, which is why the raw parameter had no effect.

--

If you are trying to read from the worksheet object directly, the `w` field of each cell stores formatted text:

```
> wb.Sheets.RkNumber.C5
{ t: 'n',
  v: 12004.55,
  w: '12004.55' }
```

--

Can you share the relevant code snipped so we could take a look?

**Comment by HugoCornu** [comment]
SheetJSDev, thanks a lot for your very clear and documented answer.
I was actually using the raw option which explains the returned result format.
Thanks
