### ISSUE TITLE
Promisify library

### ISSUE THREAD

**Issue by samsfisher** [SheetJS/js-xlsx#261]
Can this library be promisified?

I am trying to read the XL workbook in Async but apparently i am not able to get it working.

Thanks

**Comment by acicali** [comment]
Reading a workbook would normally be a synchronous operation. If you're trying to avoid tying up the UI, you can pass the read operation off to a web worker (where supported), then it would become asynchronous.

**Comment by reviewher** [comment]
@acicali hit the nail on the head. You'd have to read the whole file in order to process certain formats:

- XLSX is really a ZIP container with a bunch of sub files. You have to read a few subfiles before you can process individual worksheets, and those files can be scattered anywhere within the ZIP container. Some writers put the manifest files at the end of the ZIP

- XLS uses a simple FAT-like structure and you need to find and read the directory sectors first. Of course, some writers put the directory sectors at the end of the file so you would have to read the whole file first

So with the exception of a few uncommon formats, you really gain nothing from an asynchronous interface. 

The aforementioned suggestion of web workers is employed in the web demo http://oss.sheetjs.com/js-xlsx so in the browser that's the best approach. In node, you can use something like concat-stream to accumulate a buffer and then send the whole thing at the end.
