### ISSUE TITLE
write with styles

### ISSUE THREAD

**Issue by jinfenggt** [SheetJS/js-xlsx#266]
How can I write to excel with styles such as color,functions?

**Comment by vinodmehta** [comment]
@jinfenggt - did you figure that out?

I see some options on the cell here https://github.com/SheetJS/js-xlsx#cell-object
But not sure how to use them when writing the file out.

**Comment by fredtma** [comment]
I would like to know this as well

**Comment by aravindkoneru** [comment]
Currently, styles are not supported. There's a pull request that's being handled right now that would allow for the use of styles. Check out #128 for more info on the current state of styles. Last time I checked, the pull request was submitted, but there were some issues with the code.

**Comment by mulderp** [comment]
I did this small check on the fork, reading a file with styles and writing it. But the styles are lost:

'''
var XLSX = require('xlsx-style');

// read workbook
var workbook = XLSX.readFile('simple_excel.xlsx');

// write workbook
var wopts = { bookType:'xlsx', bookSST:false, type:'binary' };
var wbout = XLSX.writeFile(workbook, 'new_file.xlsx');
'''

**Comment by aravindkoneru** [comment]
Currently, styling is not available on this branch. The community and the developer are working together to implement styling options. You can checkout issue #128 for more info on styling. If you really need styling, I believe that there is a fork of this repo that has already implemented styling.

**Comment by MarvinBin** [comment]
Is there any update concerning the styling?

**Comment by calbertts** [comment]
Any update?

**Comment by piyushSinghalDemo** [comment]
Is there any update concerning the styling?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by rafael-andrade** [comment]
Really? The main reason to use XLSX is the styles. Hope you guys change your mind near future. I will need to switch my exportation to back-end.

**Comment by telamon** [comment]
@SheetJSDev  how is that unfair to already paid companies? They've paid money in the darkages to receive product-support where the earlier was none. 
As a company I consider my investment worthwhile if the product works as expected and I get continued maintenance. If you force the community to use a fork; then not only have you failed at promoting your own product but you have also created uncertainty which is not something any sane individual would invest in. 

You're basically failing at grasping the fundamentals of opensource; You pay for support, not for features;  My bets are always on the community when it comes to features and issues, but developer support is something only you as an legitimate entity can provide.

If the community gives you a pull-request then don't complain; instead say "thanks" and send out a happy news-letter to all your paying subscribers bragging that your product just got better or something.

I can only say that I'm discouraged from using this library after reading an backwards-thinking issue-response like this, will have to look for other alternatives.

**Comment by SheetJSDev** [comment]
@telamon At the end of the day, all work done on this open source project is charitable. In contrast to most popular and large open source projects, there are no banner ads on demo pages, no patreon or opencollective, no request for donations, no spyware or trackers or logos inserted into exported sheets, no VC backing SheetJS, nothing. We chose the very liberal Apache 2.0 License rather than try to trap companies with a license like Affero GPL. The Community Version is a passion project driven by true belief in open source, and we sacrificed thousands of hours and tens of thousands of dollars for development; testing computers and software; and documentation and support so that you and thousands of other people and companies can easily work with spreadsheets. In that spirit of open source, we continue to develop the Community version, adding features and fixing bugs ❤️

You may disagree with our pace or trajectory, but rest assured that we spent a very long time comparing options and concluded that the current path is the only one which actually gives us the autonomy and control to keep some SheetJS libraries open source and the resources to keep up with the new Office 365 monthly release cycle.  We've had multiple significant acquisition offers that we turned down because the acquiring companies want us to halt efforts on the various open source projects.
