### ISSUE TITLE
Write file with same style of template exist file?

### ISSUE THREAD

**Issue by thearabbit** [SheetJS/js-xlsx#278]
I read the `template.xlsx` with other style like `background color, border, font....`.
And then I want to write id with the same style/format.
Could you help me.

**Comment by yagoff** [comment]
I have the same problem, any help here?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
