### ISSUE TITLE
How to check whether cell is formatted as bold?

### ISSUE THREAD

**Issue by blindson76** [SheetJS/js-xlsx#286]
How to check whether cell is formatted as bold or italic?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
