### ISSUE TITLE
Opening Doc from OpenXML c#

### ISSUE THREAD

**Issue by Teyken** [SheetJS/js-xlsx#304]
I found that OpenXML c# puts x: in front of all strings in the output file.
js-xlsx can be modified to handle this by putting 

data = data.replace(new RegExp('x:', 'g'), '');

into function parse_ws_xml(data, opts, rels) and function parse_sst_xml(data, opts)

This seems to fix all problems.

**Comment by melgish** [comment]
I saw this hoping to find a work around myself.

I don't think it's as simple as that since you'd modify any cell data that actually contained x:  

At the very least the regex should be changed to only look inside tags though that still has the same drawback.  I'd prefer to see true support for whatever namespace prefix is assigned to the http://schemas.openxmlformats.org/spreadsheetml/2006/main namspace be it blank, x: or fred:

**Comment by SheetJSDev** [comment]
This was fixed, please check against latest version and raise a new issue if you find any issues.
