### ISSUE TITLE
How to add data in Header & Footer of XLSX.js Excel

### ISSUE THREAD

**Issue by alpeshsonar** [SheetJS/js-xlsx#308]
How to add data in Header & Footer of XLSX.js Excel.

**Comment by MaximMakulski** [comment]
Hey Have you already found a solution ? I need Header and Footer in my files too. And make possible to bold and set size of a coll. 

can someone help me ???

**Comment by dalenguyen** [comment]
Same here. My header and footer is missing.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
