### ISSUE TITLE
Column fully expand

### ISSUE THREAD

**Issue by mdumouchel** [SheetJS/js-xlsx#312]
Hello Everyone,
I was wondering if anyone knows if there is a option to make the column fully expand to all the contents.  

Thanks

**Comment by Jiia** [comment]
I'm trying to find a solution to this as well. The documentation is really vague about cell styles.

**Comment by SheetJSDev** [comment]
Just a short note on the feature: XLSX and XLS do not offer a flag that you can set to force Excel to recalculate the width on load.  The correct way to do this is to iterate through the cells and calculate a width based on the individual cell contents.  This is easy if the entire worksheet uses one font and one font size, but quickly ramps in complexity.

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
