### ISSUE TITLE
Freeze panes when writing an XLS file

### ISSUE THREAD

**Issue by nmalancea** [SheetJS/js-xlsx#325]
Has anyone figured out how to freeze panes using this library?
I tried many things and always get the message that the Excel file is partly unreadable and needs to be repaired.

The XML I am adding looks like this:

```
<sheetViews>
    <sheetView tabSelected="1" workbookViewId="0">
        <pane xSplit="1" ySplit="1" topLeftCell="B2" activePane="bottomRight" state="frozen" />
        <selection pane="topRight" activeCell="B1" sqref="B1" />
        <selection pane="bottomLeft" activeCell="A2" sqref="A2" />
        <selection pane="bottomRight" activeCell="B2" sqref="B2" />
    </sheetView>
</sheetViews>
```

**Comment by shapiromatron** [comment]
@nmalancea It's been almost a year - any luck ever figuring it out?

**Comment by nmalancea** [comment]
@shapiromatron Unfortunately no :(

**Comment by SheetJSDev** [comment]
@nmalancea @shapiromatron Feature requests like this are tricky because it first involves understanding the feature and how it is represented in the actual raw formats.  Let's focus on XLSX for the moment. 

Based on some testing, I think Excel XLSX cares about *where* the `sheetViews` appears in the XML file.  To test this, I saved a file with a freeze pane, then just moved the `sheetViews` block around the file.  If the sheetViews block appears just after the `dimension` tag then the file is valid, but moving the block anywhere else in the sheet file causes issues.

This is consistent with other formats too -- `MS-XLSB` worksheet binary format expects the view information to appear after the dimension record.

For example, in the XML this works:

```xml
  <dimension ref="A1:H8"/>
  <sheetViews>
    <sheetView workbookViewId="0">
      <pane xSplit="1" ySplit="1" topLeftCell="E5" activePane="bottomRight" state="frozen"/>
      <selection pane="topRight" activeCell="E1" sqref="E1"/>
      <selection pane="bottomLeft" activeCell="A5" sqref="A5"/>
      <selection pane="bottomRight" activeCell="E5" sqref="E5"/>
    </sheetView>
  </sheetViews>
  <sheetFormatPr baseColWidth="10" defaultColWidth="3.6640625" defaultRowHeight="16" x14ac:dyDescent="0.2"/>
  <sheetData>
```

This does not work:

```xml
  <dimension ref="A1:H8"/>
  <sheetFormatPr baseColWidth="10" defaultColWidth="3.6640625" defaultRowHeight="16" x14ac:dyDescent="0.2"/>
  <sheetViews>
    <sheetView workbookViewId="0">
      <pane xSplit="1" ySplit="1" topLeftCell="E5" activePane="bottomRight" state="frozen"/>
      <selection pane="topRight" activeCell="E1" sqref="E1"/>
      <selection pane="bottomLeft" activeCell="A5" sqref="A5"/>
      <selection pane="bottomRight" activeCell="E5" sqref="E5"/>
    </sheetView>
  </sheetViews>
  <sheetData>
```

(the difference is the relative location of the `sheetFormatPr`)

@nmalancea can you check if putting the `sheetViews` block directly after the `dimension` tag fixes the issue?

**Comment by reviewher** [comment]
@nmalancea @shapiromatron I think this is the right fix.  Please comment and reopen the issue if you try the solution proposed by @SheetJSDev and it doesn't work

**Comment by FinesseRus** [comment]
Could anyone share a ready JavaScript code which freezes a pane?
