### ISSUE TITLE
does this support dropdown lists?

### ISSUE THREAD

**Issue by tnrich** [SheetJS/js-xlsx#332]
For example: 
![image](https://cloud.githubusercontent.com/assets/2730609/11639805/c93526aa-9ce3-11e5-8c72-f3646a9a48c1.png)

Thank you!

**Comment by seonixx** [comment]
@tnrich When you say "support dropdown lists", what do you mean? As far as I'm aware, features such as drop down boxes are completely abstracted away from the data itself, so the value parsed for that cell will simply be whatever is currently selected as the dropdown value in the saved spreadsheet.

**Comment by nic** [comment]
+1

**Comment by SheetJSDev** [comment]
Dropdown lists are generally implemented as fixed "data validations"

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
