### ISSUE TITLE
Formula Support

### ISSUE THREAD

**Issue by ericrini** [SheetJS/js-xlsx#336]
Hello, we are currently using a C#.NET library called Aspose.Cells through edge.js and mono and would really, really like to migrate to a fully javascript\node.js implementation. The critical feature we need to have is the ability to recalculate cell formulas after writing new values into a spreadsheet and read those calculation results back.

Can anyone clarify if this library has that capability?

**Comment by XCMRyan** [comment]
It does not

**Comment by fabiooshiro** [comment]
Im writing this lib -> https://github.com/fabiooshiro/xlsx-calc

**Comment by eddyparkinson** [comment]
@fabiooshiro re:formulas - I looked at your xlsx-calc - looks handy for calculations. You could maybe pull the formulas like sum, vlookup, dget etc, from here - https://github.com/marcelklehr/socialcalc 
ethercalc uses socialcalc, working example: ethercalc.org

**Comment by fabiooshiro** [comment]
Hi @eddyparkinson I see the formulas1.js but the structure does not match.
Anyway that project is a good place to see some formulas algoritm
thx

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
