### ISSUE TITLE
IE8 and first column

### ISSUE THREAD

**Issue by Aymkdn** [SheetJS/js-xlsx#350]
So, we all know the first column is ignored when using IE8... after a few hours of debugging I found the problem is coming from `parse_ws_xml_data()`, on the [below line](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L7454):
`for(ri = typeof tag.r === 'undefined' ? 0 : 1; ri != cells.length; ++ri) {`

It should be:
`for(ri = 0; ri != cells.length; ++ri) {`

Because there is no comment in the code I don't know why there is this checking... But by changing it, then IE8 is now able to show the first column.

**Comment by SheetJSDev** [comment]
So it turns out IE does something unexpected with split on regular expressions when the first match is the beginning of a string.  To play along, try

```js
javascript:alert(['abcdef'.split(/a/).length,'abcdef'.split("a").length]) // IE
console.log(['abcdef'.split(/a/).length,'abcdef'.split("a").length]) // environments that support console
```

When you split on a string, which is the second case, both IE and other browsers will correctly generate 2 values: `["", "bcdef"]`.  For whatever reason, IE is skipping that first value entirely.

The guard 2 lines down should address the case anyway, so your proposed patch is sufficient and will be pushed in the next version.  That change works down to IE6: 

<img width="643" alt="IE6 ajax demo" src="https://cloud.githubusercontent.com/assets/6070939/23188206/beb7b9a2-f842-11e6-8a6b-b5c16595869f.png">
