### ISSUE TITLE
Write XLS?

### ISSUE THREAD

**Issue by carrbrpoa** [SheetJS/js-xlsx#353]
Hello,

Question: If the library can read Excel 97-2004 (XLS BIFF8), why can't it write this format? (Or can and I don't know how?)
What is the associated complexity?

Thanks in advance

**Comment by woomike** [comment]
I'd also like the option to save to .xls, but unfortunately it does not seem to be available.  The workaround I'm using is to use the ssconvert library and convert the newly create .xlsx file back to .xls

https://www.npmjs.com/package/ssconvert-wrapper

**Comment by David-Turbert** [comment]
duplicate #257

**Comment by SheetJSDev** [comment]
We folded XLS into XLSX and added BIFF2 XLS writing.  We will eventually add BIFF8, but for now BIFF2 works all the way back to Excel 2.0

To generate an xls file, just set `bookType:"biff2"` in the write call.  http://sheetjs.com/demos/table.html the XLS BIFF2 line demonstrates XLS writing.  

@carrbrpoa in general the difficulty with writing is ensuring that other tools can read the stuff you write.  Development-wise you can iterate a lot more quickly on the parsing side because your "success function" can be calculated once.  But if you make a mistake on the write side, you get no useful feedback on the nature of the mistake ("This file is corrupt" doesn't really tell you why the file is corrupt or where you should look to fix the issue)

For example, we test the parser by generating CSV output in excel, generating CSV output using `sheet_to_csv`, and comparing the results.  If we understand the excel file, we should be able to reproduce the CSV exactly.  That's easy to test because the baseline generation happens once.  You reuse the same csv every time you make a change.

To test the write side, you need to manually open files in various versions of excel to ensure you didn't make a mistake.  You need to look into 16 different excel versions as well as libreoffice and other tools that claim to read excel files
