### ISSUE TITLE
Macros not saved?

### ISSUE THREAD

**Issue by TennisVisuals** [SheetJS/js-xlsx#361]
I see in the README:

`The raw data is the only thing guaranteed to be saved. Formulae, formatting, and other niceties may not be serialized (pending CSF standardization)`

I see the formula present in the cell object, but it is not present when I save the workbook:
{t: "s", f: "IF(A80="","",IF(K80=1,I$1,I$2))", v: "", h: "", w: ""}

Is this not supported or is there an option that I'm missing?

Thanks!

**Comment by SheetJSDev** [comment]
@TennisVisuals the overarching problem is that every feature seems to have different representations across the Excel formats.  Take formulae, there are 4 different representations as mentioned in https://github.com/SheetJS/js-xlsx#formulae : "A1-style strings" like the example you gave, "RC-style strings" where the references are RC based rather than A1 based, "BIFF Parsed Formulae" which are a preprocessed formula format used in XLSB and XLS, and the OpenFormula standard.

At this point formulae should be saved on export.  We don't have a complete macro story yet, as that requires support for macrosheets as well as parsing and manipulating the VBA

**Comment by davidpfahler** [comment]
Unfortunately, I just ran into this as well. Macros support would be amazing.

**Comment by SheetJSDev** [comment]
To expose the VBA blob when reading a file, set the option `bookVBA:true` in the read function.  To write the VBA blob to a file, set the option `bookVBA:true` in the write function.  When feeding a VBA blob from a different workbook, the code names must be aligned.  The relevant parts are explained [in the README](https://docs.sheetjs.com/#vba-and-macros)

**Comment by creativityjuice** [comment]
Hi there,
Do you have a solution for writing "BIFF Parsed Formulae" in a xls file since March 2017 ?
I have a xls that I parse, in which I want to add stuff in cell, and finally write the new xls. It works almost perfectly when I write a xlsx, but with a xls the formula disappeared.
Is there a way to write formula in a xls with your lib ?
Anyway, thanks a lot for your job on this lib !  :ok_hand:
