### ISSUE TITLE
The currency is not read correctly from .xls file

### ISSUE THREAD

**Issue by zhang2118** [SheetJS/js-xlsx#379]
I have a currency format in my .xls file, and I tested on my project and the demo website. The currency is not parsed correctly. It parsed as NaN. The currency format that I am using is like $1,123.87. 

Is this a known issue? Will this be fixed in the future?

Thanks a lot.

**Comment by thisissami** [comment]
This is also an issue for me...

**Comment by mca22120** [comment]
Did you succeed in ? 
I have the same problem, I don't read the good value.
Have you got a solution ?

**Comment by reviewher** [comment]
@mca22120 do you have a sample file you can share?

**Comment by SheetJSDev** [comment]
I think we may have addressed this in a recent commit.  If the file came from LibreOffice, it may have generated an oddball format like `[$$-409]#,##0.00;[RED]\\-[$$-409]#,##0.00`.  We have since addressed the localization of currencies, so it should work.

We are going to close for now, but if you can share a file we can investigate further
