### ISSUE TITLE
Is there any way to get images from the excel?

### ISSUE THREAD

**Issue by barryhippo** [SheetJS/js-xlsx#381]
I want to parser excel contain images, Which function can do this?
thks

**Comment by leonardodelfino** [comment]
+1

**Comment by yamii** [comment]
+1

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
