### ISSUE TITLE
cptable var should not be exposed on the global scope

### ISSUE THREAD

**Issue by tjsail33** [SheetJS/js-xlsx#385]
While running tests using hapijs/lab, the variable leak finder reported `The following leaks were detected:cptable`. It would be greatly appreciated if this could be scoped so that it was not global by defining `var cptable` at the top of the file, the same way you define `var XLS`. Thanks!

**Comment by reviewher** [comment]
@tjsail33 This is intentional since `cptable` is an "optional dependency".  XLS format uses the codepage functionality but it is not needed for XLSX format.  As the codepage source is 378kb, it seemed inappropriate to make it required if you are only using XLSX, so it is optional and the code checks if the variable is available in a browser context.

https://github.com/SheetJS/js-xlsx/blob/master/index.html#L46-L49 if you are including the source with standard HTML script tags, putting `var cptable;` up at the top of xlsx.js would mask the cptable variable inherited from execution of the cpexcel script.

If there are magic comments that we can include to appease your test runner, that might be the better approach.  We already have some comments for jshint.

**Comment by gabegorelick** [comment]
> putting var cptable; up at the top of xlsx.js would mask the cptable variable inherited from execution of the cpexcel script.

Can't you read it off `window/global`?
