### ISSUE TITLE
How to Add Data Validation

### ISSUE THREAD

**Issue by shahbhaveshp** [SheetJS/js-xlsx#387]
Hi,
    I want to add datavalidation for a cell (Lookup values with dropdown). 
    Is it supported in current version?
    Let me know.

Thanks,
Bhavesh

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
