### ISSUE TITLE
Is there is small lib for read excel to json ?

### ISSUE THREAD

**Issue by ghost** [SheetJS/js-xlsx#388]
in my case, i need to convert simple data from excel to json.
it will be nice if a have a small version of this project without ability to create, just to read excel and convert to json or csv.
and i think this small lib will be < 400KB..

**Comment by vincenthan13** [comment]
+1 for this question. somebody out there to help solving this problem

**Comment by SheetJSDev** [comment]
@hierarchy @vincenthan13 tl;dr unless you are supporting only a very specific file or format, 400kb is likely insufficient.

"excel" file encompasses many different and complex formats.  https://support.office.com/en-us/article/File-Formats-supported-in-Excel-for-Windows-b3ef04b4-6078-4c0d-b69e-a00ef58f467f is a list just for Excel 2016/2013, there are other lists like https://support.office.com/en-us/article/file-formats-that-are-supported-in-excel-a28ae1d3-6d19-4180-9209-5a950d51b719 for Excel 2007.

Even for a specific format, unless it is a very simple data format like CSV/TSV, the implementation is necessarily big since you have to effectively "bring your own ecosystem".  For example, XLSX files are really ZIP files at the end of the day, so you need a way to read them.  [The implementation is already more than 250kb](https://github.com/SheetJS/js-xlsx/blob/master/jszip.js).  If you were writing a C program you would just use info-zip / zlib but you don't have that luxury in a general JS context -- you have to bring your own.  XLS files have a [simpler container](https://github.com/SheetJS/js-cfb/blob/master/cfb.js) but now you need a [350kb file](https://github.com/SheetJS/js-xlsx/blob/master/dist/cpexcel.js) to be able to read text stored in cells.

**Comment by WaSheep** [comment]
same issue + 1, is there any plugin just like` babel-plugin-lodash`
