### ISSUE TITLE
How to create dropdown values column on export in sheetjs

### ISSUE THREAD

**Issue by Amitloh** [SheetJS/js-xlsx#452]
How to create dropdown values column on export in sheetjs(yes/no)

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
