### ISSUE TITLE
AA1, AB1 double row addresses don't write to the xlsx

### ISSUE THREAD

**Issue by clovissix** [SheetJS/js-xlsx#460]
Hi,

As soon as I start using the following cell addresses: AA1, AB1, the writer doesn't seem to properly write it to the xlsx anymore.

Here is a part of one of my sheets:
  'T426': { v: '1 (Zeer Eens)', t: 's' },
  'U426': { v: '1 (Zeer Eens)', t: 's' },
  'V426': { v: '1 (Zeer Eens)', t: 's' },
  'W426': { v: '1 (Zeer Eens)', t: 's' },
  'X426': { v: '1 (Zeer Eens)', t: 's' },
  'Y426': { v: '4 (Oneens)', t: 's' },
  'Z426': { v: '4 (Oneens)', t: 's' },
  'AA426': { v: '4 (Oneens)', t: 's' },
  'AB426': { v: '5 (Zeer Oneens)', t: 's' },
  'AC426': { v: 'Antwerpen', t: 's' }

When I stop at Z, it still works.
Is there any param I need to set?

Regards,
Clovis

**Comment by SheetJSDev** [comment]
@clovissix I would guess it's a range issue.  I just tested by modifying the [write sample](https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js) with a 29-column row:

```js
var data = [
        [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9], // 29 cells
        [true, false, null, "sheetjs"],
        ["foo","bar",new Date("2014-02-19T14:30Z"), "0.3"],
        ["baz", null, "qux", 3.14159]
];
```
Here are the generated files (since github doesn't support uploading certain formats, remove the `.zip` extension for those files):

- [sheetjs.xlsx](https://github.com/SheetJS/js-xlsx/files/836867/sheetjs.xlsx)
- [sheetjs.xlsb.zip](https://github.com/SheetJS/js-xlsx/files/836868/sheetjs.xlsb.zip) 
- [sheetjs.ods.zip](https://github.com/SheetJS/js-xlsx/files/836869/sheetjs.ods.zip) 
- [sheetjs.fods.zip](https://github.com/SheetJS/js-xlsx/files/836872/sheetjs.fods.zip)
 
Can you check what the sheet's `'!ref'` property shows as the worksheet?

**Comment by SheetJSDev** [comment]
@clovissix please reopen or leave a comment if the issue shows up again.
