### ISSUE TITLE
Numeric columns

### ISSUE THREAD

**Issue by stla** [SheetJS/js-xlsx#465]
Hello,
 The `readFile` function returns a string for each cell. Is there a way to get the numeric columns in numbers ?

**Comment by reviewher** [comment]
@stla do you have a sample file that shows this problem?  If you write strings in the file, then readFile will interpret as text.  If you store numbers in the file, readFile should give numbers.

If you have a copy of excel handy, try setting A1 to `1` and A2 to `'1` (apostrophe followed by 1).  The apostrophe forces plaintext interpretation so A2 will save the literal text `1` and not the numeric value `1`.  You will see that A2 is left-aligned and there will be a warning since Excel is interpreting the value as text.

Related article: https://support.office.com/en-us/article/Fix-text-formatted-numbers-by-applying-a-number-format-6599C03A-954D-4D83-B78A-23AF2C8845D0

**Comment by stla** [comment]
I don't remember this issue... I'll give a try later but probably I did something wrong.

**Comment by reviewher** [comment]
@stla it sounds like an issue with the data source.  Do you remember where the files would have come from?  Some third party writers don't always do the right thing.

**Comment by SheetJSDev** [comment]
@stla if you remember the issue please raise a new one.  Closing this for now.

**Comment by stla** [comment]
Yes, sorry for not having replying. Surely I did something wrong, there's no such issue.Thank you for taking care of this awesome library.Cheers. 

    Le Mardi 21 février 2017 10h37, SheetJSDev <notifications@github.com> a écrit :
 

 @stla if you remember the issue please raise a new one. Closing this for now.—

**Comment by reviewher** [comment]
@stla If a file can be read with Excel but can't be read with the node module or the web demo, or if the results are different, then we have a bug.  There are specifications like [ECMA-376](http://www.ecma-international.org/publications/standards/Ecma-376.htm), and there are specifications for how Excel may deviate from the original specifications like [MS-XLSX](https://msdn.microsoft.com/en-us/library/dd922181.aspx), but Excel oftentimes deviates from both of those specifications.  The whole thing is a black box!  So if you have a problematic test case, surely our understanding differs from Excel's actual behavior and we should improve our end.
