### ISSUE TITLE
Copy and paste is not working on downloaded excel file

### ISSUE THREAD

**Issue by ramstheroyal** [SheetJS/js-xlsx#470]
Hi,
    Excel sheet is getting created and downloaded properly but the problem is with COPY and PASTE in the sheet.
  Once the sheet got downloaded, if we try to COPY the cell content and PASTE it in some other sheet, its giving 'The command cannot be used on multiple selections'.

![image](https://cloud.githubusercontent.com/assets/11647390/18630242/bf9d1f6c-7e88-11e6-9283-ed687b264694.png)

Even the same error is getting displayed, when we try to create a new sheet to the downloaded file.

![image](https://cloud.githubusercontent.com/assets/11647390/18630285/1e89ac98-7e89-11e6-9e6c-9ce818ca756a.png)

Here is the piece of code which is used:

```
  var wb = new Workbook(),
                ws_name = config.name || 'GTMS',
                ws = sheet_from_array(metaData, data, query);

            /* add worksheet to workbook */
            wb.SheetNames.push(ws_name);
            wb.Sheets[ws_name] = ws;
            if (config.download) {
                var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
                saveAs(new Blob([s2ab(wbout)], {
                    type: 'application/octet-stream'
                }), config.fileName);
            } else {
                return ws;
            }
```

// here data and metaData are in JSON format.

Can somebody help?

**Comment by orau-dev** [comment]
Hi!
We are experiencing the same problem and we figured it out to be an Excel issue. It has to do with Enable Editing when Excel is in the Protected View. Simply, when the excel file is generated and opened, at the top, underneath the menu in excel is a message like this:

![protected view](https://cloud.githubusercontent.com/assets/26419399/23922344/5d05752c-08d8-11e7-95a6-6dd0e2348b2c.PNG)

While in protected View, you can copy and paste anything into another workbook as you would expect. If, however, you push the Enable Editing button, you will get the Excel error as mentioned above. If you save the file instead of opening it, you will encounter the same error when you open the file again. You can just open the file, save it and reopen it, you can also avoid the problem.
The following link describes the issue and the solution as directed my Microsoft:
https://community.dynamics.com/crm/f/117/t/168778

**Comment by SheetJSDev** [comment]
@orau-dev thanks for the report!  Is there any way we can change the generated file to avoid this issue?  Does it show up with XLSB export or with any of the other formats?

**Comment by orau-dev** [comment]
@SheetJSDev, That is my next step. I'll let you know in the next few days. The hard part was focusing the symptom to the actual problem.

**Comment by orau-dev** [comment]
@SheetJSDev, I looked at other formats and it seems to still be a problem. I also looked at Excel options, with no solution. It appears to be an Excel bug. In our case, we really need the file to be in xlsx format and using any other format is a nonstarter.

**Comment by orau-dev** [comment]
@SheetJSDev, on another note (not sure the best place to communicate with you without dirtying this tread), I use this Excel library from a TypeScript class. I have a type definition file and a wrapper class that makes reading and writing excel files easier for me. Are you interested in them? You may need to test and/or modify to fit your scheme.

**Comment by SheetJSDev** [comment]
I tried but cannot reproduce the issue using http://sheetjs.com/demos/table.html with Chrome/Excel2016/Windows 7.  I clicked the "Export to XLSX!" button and it generates a file, I see that protected warning when I open the file, but I can add a sheet to the downloaded file and I can copy-paste without any warnings.

@orau-dev can you generate a simple file which shows this problem?  I can hand-craft files with the issue by writing multiple worksheets with selection, but the writer currently does not write any `sheetView` or `selection` information.  If you can't share it, can you start a web server, "upload" the file, and re-download it with your web browser (so we can see if this is an issue specific to client-side generation)?  If you want to send it directly to me, dev@sheetjs.com works.

And @orau-dev yes we would be interested in a good type definition file!

**Comment by orau-dev** [comment]
I tried your demo and interestingly, I don’t get the problem either. So I’m baffled. I believe you saw the link to Microsoft admitting a bug. But, your test file doesn’t produce the issue. The only difference I think between my file and one the demo generates is my file applies styles to the cells. There could also be some underlying formatting attributed to the way the cells are formatted in javascript. But, I’m only guessing.

**Comment by SheetJSDev** [comment]
@orau-dev @ramstheroyal If you are using the @protobi fork with styles, you are probably seeing https://github.com/protobi/js-xlsx/issues/26  I assume the warning about files from the Internet cannot be suppressed.

**Comment by orau-dev** [comment]
Ah,
You are right. I am using the forked version. However, I think I’m using a later version than is referenced. I’ll look into it. But, thanks!

John R. Riesenberg | Senior Tool Developer | NIOSH Dose Reconstruction Team | Dade Moeller<http://www.dademoeller.com/> – an NV5<http://www.nv5.com/dade-moeller-is-now-nv5/> Company
P: 513.777.0277 | C:513.235.6891

**Comment by jamezrgomez** [comment]
Hi @orau-dev and @SheetJSDev !
While the Libre Office and Calligra Suites give me absolutely no problem on Ubuntu, Excel has driven me round the bend on Windows. What is the current state of this issue?

Also, one of these may be of help for those who'd just like to manipulate the file (rather than incorporate the code without this problem into their system) : 

1) https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_mac-mso_mac2016/this-action-wont-work-on-multiple-selections/33bdfd4d-c59d-4061-af02-78786b1d37eb
2) https://answers.microsoft.com/en-us/msoffice/forum/all/alert-this-action-wont-work-on-multiple-selections/d22c8b6d-4f3c-485f-ac3c-f94e80b01ebf
3)https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_mac-mso_mac2016/excel-2016-mac-version-16141-cannot-movecopycreate/30b5be75-d3be-4452-b93c-40057a2bae1e
