### ISSUE TITLE
Transfer ownership or add moderator

### ISSUE THREAD

**Issue by jimmywarting** [SheetJS/js-xlsx#500]
Seems like you haven't done anything for about 2 years, ppl still want to help with PR so let them do that somehow

**Comment by reviewher** [comment]
In the past there were many long-winded comments that focused on specific points.  Here is my summary of the PR logistics, let me spare you the pain:

- there are [other JS libraries with some onerous terms like platform limitations](https://github.com/stephen-hardy/xlsx.js/blob/master/LICENSE.txt#L22) that basically muddied the waters so we must be extra vigilant when accepting code

- before even thinking about looking at other people's code, developers must make sure to comply with the [Microsoft OSP](https://msdn.microsoft.com/en-us/openspecifications/dn646765.aspx).  That's why there is a comment in the README: https://github.com/SheetJS/js-xlsx#license

- People do not generally consider the various corner cases.  [The conversation in a previously merged PR](https://github.com/SheetJS/js-xlsx/pull/43) shows the importance of looking at various cases to understand the scope of each feature.

- The project is tested against various versions of Excel, a largely manual and time-consuming process that is tricky to automate.

As a whole it takes a significant amount of time and risk to properly evaluate even seemingly trivial changes.  Even though it isn't explicitly said anywhere, I get the sense that few people in the community have the time, patience, discipline, access to various versions of Excel, and desire to volunteer and help maintain the project.  FWIW developers in other projects like LibreOffice don't have the right attitude, as evidenced in [a LO bug report](https://bugs.documentfoundation.org/show_bug.cgi?id=83511):

> We [LibreOffice] ignore the last two bits for many stuff to improve the user experience.

On a side note: I've personally stopped recommending LO as an alternative to Excel after reading that issue and response, when I realized they weren't even bothering to try to align with Excel on basic math.  The meme "you had one job" feels appropriate here.

Further reading:

- https://github.com/kennethreitz/tablib/issues/114 is a really nice roundup of python modules and their origins.  If you are remotely curious about licensing issues, the whole python excel space is a licensing quagmire

- https://github.com/stephen-hardy/xlsx.js/issues/8 discusses the "Platform Limitation" clause of a JS library and various implications.  

- https://github.com/SheetJS/js-xls/issues/1#issuecomment-13852286 explains the warning in the README

- https://github.com/SheetJS/js-xlsx/issues/513#issuecomment-269859459 discusses some of the non-obvious social issues at play
