### ISSUE TITLE
Fork for community contributions.

### ISSUE THREAD

**Issue by karlbateman** [SheetJS/js-xlsx#502]
As this hasn't been updated in a while and with some important issues which need to be addressed, might I suggest that someone propose a fork and provide a URL so that the community can bring this project forward.

Assuming of course that the maintainer can no longer continue.

This is a great library and I would really like to this evolve, if I had more time I would offer more involvement. I hope that there maybe someone who could help. 😄

**Comment by moxious** [comment]
For those who don't already have too much code built, there's also this: https://github.com/guyonroche/exceljs

**Comment by tarwich** [comment]
I've made a fork at [tarwich/js-xlsx]. Feel free to PR anything you want over there. Hopefully the community fork will grow. However, I [have been told] that these guys are in fact maintaining -- they're just slow due to being thorough. 

[tarwich/js-xlsx]: https://github.com/tarwich/js-xlsx
[have been told]: https://github.com/SheetJS/js-xlsx/issues/513#issuecomment-267741561

I agree with you that these guys have done awesome work. Hopefully they find ways to improve testing so things aren't so hard for them.

**Comment by eddyparkinson** [comment]
**Organization account**
tarwich Created an Organization account - https://github.com/node-xlsx
Let me know if you want adding.

https://github.com/blog/674-introducing-organizations
