### ISSUE TITLE
Error: "Cannot find Workbook stream" when reading Excel 2007 .xlsx file with protected workbook 

### ISSUE THREAD

**Issue by franzweitl** [SheetJS/js-xlsx#511]
First, thanks for the great tool!

When reading an .xlsx file with password protected workbook structure, which was saved by Excel 2007 , I get the following error (xlsx.js version 0.8.0):

Error: Cannot find Workbook stream  xlsx.js:9828:13

When the same file with same workbook protection is saved with newer versions of Excel, the error does not occur and the workbook object can be successfully read.

```
private loadFile(fileInputChange:Event): void {
          let file = (fileInputChange.target as any).files[0];
          let reader:FileReader = new FileReader(); 
          reader.onload = function(e) {
              let data = (e.target as any).result;
              let workBook = XLSX.read(data, {type: 'binary'});
              console.log(workBook);
          }
          reader.readAsBinaryString(file);
}
```

**Comment by SheetJSDev** [comment]
There are two types of "workbook protection": "encrypt with password" and "protect workbook structure":

<img width="249" alt="protect" src="https://cloud.githubusercontent.com/assets/6070939/24995264/3d502ade-1ffc-11e7-819f-0401c104536f.png">

The latter merely adds a record to the file that disables normal editing, but otherwise leaves the file as-is.  It's a pretty simple feature and we can read/write it! https://github.com/sheetjs/js-xlsx#worksheet-object see the `!protect` bullet point.

The former is much more complex.  The file is actually encrypted and we would have to manually perform the decryption algorithm.

**Comment by reviewher** [comment]
Closing in favor of #774
