### ISSUE TITLE
Determining Cell formatting like fill color and border

### ISSUE THREAD

**Issue by gcoonrod** [SheetJS/js-xlsx#52]
Can js-xlsx be used to determine the formatting of a cell? Specifically, I need to be able to  find cells with specific fill colors.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
