### ISSUE TITLE
How to reduce the file size?

### ISSUE THREAD

**Issue by tommytian770401** [SheetJS/js-xlsx#520]
I use js-xlsx as excel parser to generate json array|object,  when output the xlsx file using the same data with blob.js and filesaver.js simply follow the way described in the demo.  It worked fine but the  size of outputs is amazing larger(almost 10 times) than the original one. I tried the csv format, no such fileSize issue, but it will cutdown the flexibility.

I do not know the background exactly,  i guess the blob added tons of info. After open and save  the xlsx file generated, the size change and shrink reasonable. Is there any way to control or reduce the size when using blob? 

It will be very helpful to give some advices. thanks a lot.

**Comment by ragingpatatot** [comment]
jszip has a compression option, js-xlsx just needs to expose it

**Comment by tommytian770401** [comment]
@ragingpatatot , you mean output the zip file. It's a nice option. I'll try it, and see the result.

**Comment by SheetJSDev** [comment]
Currently the `compression` write option instructs the zip library to compress files.  See https://github.com/SheetJS/js-xlsx/#writing-options.

As an example:

```js
XLSX.writeFile(workbook, 'out.xlsx', {compression:true});
```

**Comment by mobilfid** [comment]
{compression:true} does not seem to do anything. I am reading a 18 KB file and after writing, it keeps becoming 1,1 MB.

Any other suggestions?

**Comment by CodeBroJohn** [comment]
Setting compression to true does decrease the file size for me, however the generated file is still over double the size of the same data should I just generate and save it directly in excel. I have looked into why this may be, and tried several things but have not had any luck getting the file size closer to the size when using excel directly.

**Comment by edgedemon** [comment]
I would had preferred not to do this, because i do appreciate the work sheetJS has done, but i've found the file size between this community edition and the fork at [https://github.com/ShanaMaid/sheetjs-style](sheetjs-style) is twice as big, i suspect the issue happens when they removed the styles for the community edition, comparing the produced files i see the one from SheetJS showing a "predetermined" font, i suspect is actually loading a whole font into the file while removing the original style instead of just setting an existing default one.
![image](https://github.com/SheetJS/sheetjs/assets/5783253/bb16b0f1-f047-4186-b9d4-69696fdb3b56)
