### ISSUE TITLE
CSV and JSON output differs

### ISSUE THREAD

**Issue by andreasgremm** [SheetJS/js-xlsx#522]
Hello,
With the attached xslx the column values in csv and json are different.

For example pls. see the row for "Mettmann" where in csv and json the column values differ. The csv values seem to be correct.

Kind regards,
Andreas

[2017 Lehrgangsverteilung KFV überarbeitet.xlsx](https://github.com/SheetJS/js-xlsx/files/680831/2017.Lehrgangsverteilung.KFV.uberarbeitet.xlsx)

**Comment by reviewher** [comment]
Hello Andreas!

I took a look at your file and checked your file against http://oss.sheetjs.com/js-xlsx/ (the source is in the gh-pages branch).  It looks like some automated output from a tool, but the JSON output is roughly what I would expect:

1) According to the file, the range of the workbook is A1:AMK22.  If you want to verify that manually, change the extension to `.zip`, extract and view the file xl/worksheets/sheet1.xml.  After beautifying the xml,  you will see a line

```xml
<dimension ref="A1:AMK22"/>
```

AMK is column 1025 (assuming A is 1) and is far beyond the extent of the data.  The CSV writer leans on the sheet's reported range which is why you see a slew of commas at the end of each line.

2) Based on the colors and text orientation, it looks like the first 5 rows are headers.  the JSON logic is pretty simple and only reads the first line as a header row.  A1 is empty which is why the data in A6:A22 show up in an unexpected place.

If you want to skip the whole header logic, pass the option `header:1` to the writer.  In node:

```
> var XLSX = require('xlsx')
> var xlsx = XLSX.readFile('Downloads/2017.Lehrgangsverteilung.KFV.uberarbeitet.xlsx')
> XLSX.utils.make_json(xlsx.Sheets.Tabelle1, {header:1})
```

@andreasgremm can you try passing the header option and see if the output aligns with the CSV output?

3) The negative numbers are rendered with 2 hyphens.  This is clearly a bug.

Dev Note: The format code according to the Excel UI is `0_ ;[Red]-0 `.  The file has the format saved as `0_ ;[Red]\-0\ `. The formatter erroneously interprets the hyphen as literal when it is in fact a sign hyphen.

**Comment by andreasgremm** [comment]
Hello,
thanks for the information I testet the header:1 option. The output differs but seems to be ok from what I see out of the values.
Kind regards,
Andreas
