### ISSUE TITLE
What does the cellStyles look like?

### ISSUE THREAD

**Issue by panshiyao** [SheetJS/js-xlsx#530]
I am exporting an excel which have some styles like bold by the `XLSX.write`. But I went through the `readme` and there are no explain about what the property of `cell.s` looks like. Is there a format or demo about it?

**Comment by eddyparkinson** [comment]
This version has style support - https://github.com/protobi/js-xlsx  by https://github.com/pietersv
We plan to merge it into the community version https://github.com/quilt-js

We are  working on a community version, a "Current, latest features" version. Because of https://github.com/SheetJS/js-xlsx/issues/513

**Comment by eddyparkinson** [comment]
Styles - suggest this fork for styles https://github.com/protobi/js-xlsx 

Pull requests welcome here https://github.com/quilt-js/js-xlsx 
because https://github.com/SheetJS is more of a LTS version

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
