### ISSUE TITLE
js-xlsx : preserve cell style while writing to .xlsx file

### ISSUE THREAD

**Issue by sumxyz** [SheetJS/js-xlsx#543]
I have been trying to figure this for a while now. Please help.

I have manually created a .xlsx file. I have added different colors to some rows and some of the cells have custom date format.

I am using js-xlsx npm module to read data from .xlsx file. While writing back to the same .xlsx file to update some cell values, the selected colors and date formats are lost.

I tried below code but that did not help preserve the .xlsx cell styles.

I did npm install xlsx-style.

```
    var XLSX = require('xlsx');
    XLSX.readFile('abc.xlsx', {cellStyles: true});
        var first_sheet_name = workbook.SheetNames[1];
        var address_of_cell = 'A1';
        var worksheet = workbook.Sheets[first_sheet_name];
        var desired_cell = worksheet[address_of_cell];
        var desired_value = desired_cell.v;
        desired_cell.v = 'efg';
   XLSX.writeFile('abc.xlsx', {cellStyles: true});
```

**Comment by eddyparkinson** [comment]
Styles - suggest this fork for styles https://github.com/protobi/js-xlsx

Pull requests welcome here https://github.com/quilt-js/js-xlsx
because https://github.com/SheetJS is more of a LTS version

**Comment by gzll** [comment]
I meet a same problem. need help. thanks

**Comment by sskarabej** [comment]
In this fork you have options to set cell styles: https://github.com/protobi/js-xlsx
Author made pull requests, but the original developers are being careful about merging, especially on the write side due to compatibility with large amount of Excel versions and other spreadsheet creating/editing tools.
See the discussion here [https://github.com/protobi/js-xlsx/issues/21](url)

If you'd like to use creating files solely on the server side, check out [https://github.com/guyonroche/exceljs](url)

**Comment by reviewher** [comment]
@sumxyz The simplest approach, especially if you have a file with macros or other complicated features, is to use a minimally-invasive module like [`xlsx-template`](https://www.npmjs.com/package/xlsx-template) or [`xlsx-populate`](https://www.npmjs.com/package/xlsx-populate). See https://github.com/SheetJS/js-xlsx/issues/121#issuecomment-272371902 for a longer explanation.  Instead of trying to parse the XLSX file, they just scan the XML and apply changes directly.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by m4r3x** [comment]
Personally - I think it's unfair for those that chosen your library and came into issue of styles being silently ignored and forced to go into Pro version. You should update your README.md and exclude documentation about features that are not available. It's not big deal for you and can help save other people time. Cheers :)
