### ISSUE TITLE
cellStyles: bgColor doesnt return colors

### ISSUE THREAD

**Issue by alexmilde** [SheetJS/js-xlsx#555]
Hi 
thanks for the library. really apreciate it!
however i have some issues with bgColor reading.
i can access the .s style node but it only holds an "indexed" property.
for various colors the index won't change.

any advice on this?
best
alex
 
[Excel-Test.xlsx](https://github.com/SheetJS/js-xlsx/files/764065/Excel-Test.xlsx)
![bildschirmfoto 2017-02-09 um 16 14 44](https://cloud.githubusercontent.com/assets/2182118/22789316/e6cb610a-eee2-11e6-9a8e-2fcf576ecd69.png)
[test.html.zip](https://github.com/SheetJS/js-xlsx/files/764071/test.html.zip)

**Comment by gongph** [comment]
#587  Hi, You can look this about sheetDev‘s repay!

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by xalakox** [comment]
I have the pro version, and is not returning the right bgColor, I always get #FFFFFF @SheetJSDev
