### ISSUE TITLE
Skipping empty fields in Sheet object

### ISSUE THREAD

**Issue by ggunia** [SheetJS/js-xlsx#559]
If some cell is empty in xls document, this cell is not included in sheet object at all. Is there any way to avoid this behaviour?

**Comment by reviewher** [comment]
The XLS parser will only generate cells if the file specifies them.  There are three general circumstances of "missing cells":

- Cells outside of the stated range are not generated.  For example, if you have content in cells A1:C3 you won't see a cell object at address XAA1000000.  This is intentional, otherwise browsers would blow up if we added cell objects for every possible cell.  Excel 2007+ have a hard limit of 17B cells (1048576 rows 16384 columns) so it's easy to see why you wouldn't want to create cells for every valid reference.

- Sometimes the file itself does not include the cells in the first place.  For example, if you have a "jagged" unformatted table like

```
| A | B | C |
| F |   | J |
| D | E |   |
| G | H | I |
``` 

then the file itself will not include records for those missing cells.

- Other times the file stores stub cells, and you can instruct the parser to generate those stubs with the [`cellStubs`](https://github.com/SheetJS/js-xlsx#parsing-options) option.

The simple answer: 

- if your file doesn't specify the cell in any capacity, either as a `Blank` record or as an actual cell, the parser won't automagically generate a reference.

- if your file does specify the cell as a `Blank` record, setting `cellStubs` to true should be sufficient.

---

If you want to find whether the file includes the cell in question, in the `parse_workbook` function uncomment the line

```
			console.error(R,blob.l,length,blob.length);
```

The actual XLS content is stored as a series of binary records, and that code will print out some information about every record it encounters.  For the aforementioned example, if you uncomment the line and test with no formatting you will see a block of lines in the console like

```
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15442 10 15686 // <-- A1 "A"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15456 10 15686 // <-- B1 "B"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15470 10 15686 // <-- C1 "C"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15484 10 15686 // <-- A2 "F"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15498 10 15686 // <-- C2 "J"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15512 10 15686 // <-- A3 "D"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15526 10 15686 // <-- B3 "E"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15540 10 15686 // <-- A4 "G"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15554 10 15686 // <-- B4 "H"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15568 10 15686 // <-- C4 "I"
```

Those are references to the cells with content.  If you bold the block A1:C3 and then italicize column B, Excel will generate stubs:

```
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15745 10 16009 // <-- A1 "A"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15759 10 16009 // <-- B1 "B"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15773 10 16009 // <-- C1 "C"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15787 10 16009 // <-- A2 "F"
{ n: 'Blank', f: [Function: parse_XLSCell] } 15801 6 16009      // <-- B2 ***
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15811 10 16009 // <-- C2 "J"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15825 10 16009 // <-- A3 "D"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15839 10 16009 // <-- B3 "E"
{ n: 'Blank', f: [Function: parse_XLSCell] } 15853 6 16009      // <-- C3 ***
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15863 10 16009 // <-- A4 "G"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15877 10 16009 // <-- B4 "H"
{ n: 'LabelSst', f: [Function: parse_LabelSst] } 15891 10 16009 // <-- C4 "I"
```
