### ISSUE TITLE
Dealing with xlsx empty fields

### ISSUE THREAD

**Issue by muscaiu** [SheetJS/js-xlsx#562]
Hi, I'm trying to read an xlsx file, and add all the fields in a DB exactly as they are in the Excel file.

How can i do that if the **empty fields can't be detected**?

![xlsx](https://cloud.githubusercontent.com/assets/11426309/23069658/f31d4ea6-f530-11e6-863f-623d11279ef9.jpg)

**Comment by SheetJSDev** [comment]
They are missing from the file in the first place.  I repeated that exact sheet and Excel 2016 XLSX generated the following XML:

```
    <row r="1" spans="1:2" x14ac:dyDescent="0.2">
      <c r="A1" t="s">
        <v>0</v>
      </c>
      <c r="B1" t="s">
        <v>1</v>
      </c>
    </row>
    <row r="2" spans="1:2" x14ac:dyDescent="0.2">
      <c r="A2" t="s">
        <v>2</v>
      </c>
      <c r="B2" t="s">
        <v>3</v>
      </c>
    </row>
    <row r="3" spans="1:2" x14ac:dyDescent="0.2">
      <c r="A3" t="s">
        <v>4</v>
      </c>
    </row>
    <row r="4" spans="1:2" x14ac:dyDescent="0.2">
      <c r="A4" t="s">
        <v>5</v>
      </c>
      <c r="B4" t="s">
        <v>6</v>
      </c>
    </row>
    <row r="5" spans="1:2" x14ac:dyDescent="0.2">
      <c r="B5" t="s">
        <v>7</v>
      </c>
    </row>
    <row r="6" spans="1:2" x14ac:dyDescent="0.2">
      <c r="A6" t="s">
        <v>9</v>
      </c>
      <c r="B6" t="s">
        <v>8</v>
      </c>
    </row>
```

You can see Excel omits empty cells in the first place, which is why you won't see those cells when read by xlsx.  If you want to re-introduce those cells, you could loop the rows and columns of the sheet (see the `sheet_to_csv` function -- it has to loop and write an empty string for missing cells)
