### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/js-xlsx#589]
Simplify the build and test process to enable a Windows development workflow

see https://github.com/SheetJS/js-harb/issues/7 h/t @simon-p-r

**Comment by simon-p-r** [comment]
Happy to help with any testing!

**Comment by SheetJSDev** [comment]
@simon-p-r starting from a fresh windows setup we were able to build the source and run the tests!

https://github.com/sheetjs/js-xlsx#windows is the relevant part of the documentation.

Configuration Steps:

1) `git clone https://github.com/SheetJS/js-xlsx/`
2) download the test files snapshot https://github.com/SheetJS/test_files/releases/download/20170409/test_files.zip
3) extract that to the test_files subdirectory in the source tree
4) `npm install -g mocha` and `npm install`

After making changes to the bits files, `make.cmd` will rebuild xlsx.js and `mocha -t 30000` will run tests.

**Comment by simon-p-r** [comment]
I will have a go and let you know if there are any problems

**Comment by reviewher** [comment]
@simon-p-r updated the make.cmd script to streamline the process.  Tested on an old Surface Pro 3 running windows 8.1 and everything seemed to work!  Since we aren't using any powershell features it should work back to Windows 7.

Preparation:
- Install node (6.10.2 in this test but other versions work too)
- Install git windows (2.12.2.2 in this test), use default options (`core.autocrlf = true`)
- Download the test files release from [the test_files repo](https://github.com/SheetJS/test_files/releases)

Commands:
- `make init` to install dependencies and dev modules
- `make` will build the source
- `make lint` will run the linter
- `make misc` will run a small set of tests
- `make test` will run the full tests
- `make book` will update the README from the docbits.
