### ISSUE TITLE
Is it possible to add image to header?

### ISSUE THREAD

**Issue by garyganyang** [SheetJS/js-xlsx#601]
Hi guys, 
i want to add watermarks to excel,  i found that xlsxwriter(python) can do it easily by setting an image to header like `worksheet.set_header('&C&G', {'image_left': 'logo.jpg','margin': 4})`, 
then you can see it in “Page View/Layout” mode by setting pageView like `worksheet.set_page_view()`.

can this exceljs do the same thing? im longing for that, , many thanks in advance.

**Comment by SheetJSDev** [comment]
At the moment neither images nor headers are supported, but we've added that to the queue of topics to address.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
