### ISSUE TITLE
Is it possible to filter out "hidden" rows?

### ISSUE THREAD

**Issue by janvanderhaegen** [SheetJS/js-xlsx#630]
We're using SheetJS to import data. 
When a workbook is parsed, every cell is included. However, our users seem to have two scenarios where they wanted to exclude data
*  They hide the entire row (right-click on row, click "Hide")
*  They have a table with headers, and have filtered on specific values

In either or both of the cases above, when they open the workbook in excel they'll see only the filtered data, yet when they import that sheet into our web app they see all cells.

Is there a way for us to find out if a row is hidden?
Is there a way for us to find out if there is a table, and it has filters applied?

Thanks in advance

**Comment by SheetJSDev** [comment]
We added autofilter information to the repo but haven't released it yet.  The other details aren't currently exposed.  Stay tuned.

**Comment by SheetJSDev** [comment]
Row and column visibility are now exposed in the row/column metadata.  I explained it [in a different comment](https://github.com/SheetJS/js-xlsx/issues/588#issuecomment-297932103), but the code looks like this:

- `!!((worksheet['!rows']||[])[R]||{}).hidden` is `true` if row `R` is hidden and `false` otherwise.  
- `!!((worksheet['!cols']||[])[C]||{}).hidden` is `true` if col `C` is hidden and `false` otherwise.

**Comment by janvanderhaegen** [comment]
Thanks champ!

**Comment by ashishzestiot** [comment]
Hey guys 
I want to hide multiple columns in exported excel file in Angular, how do we can?

**Comment by kingofnull** [comment]
You can parse the sheet to csv while removing hidden rows and reparse it. You can find the code [here](https://stackoverflow.com/a/70997580/4238323)
