### ISSUE TITLE
How to convert XLS to JSON in browser.

### ISSUE THREAD

**Issue by chanakaDe** [SheetJS/js-xlsx#635]
I have a simple requirement. Just upload a file to my web application (a XLS file) and convert it to JSON.
<script lang="javascript" src="dist/xlsx.core.min.js"></script>
I imported xlsx to my application like this.
But following command gives me an error.

> var workbook = XLSX.readFile('test.xlsx');

Can anyone tell me how to make this work ?
Sample code please. I don't have a node.js server. Just need to convert XLS to JSON in front end using normal js codes.

**Comment by SheetJSDev** [comment]
Some people have had success with the directive https://github.com/brexis/angular-js-xlsx -- try it out and let us know if you have any problems

**Comment by chanakaDe** [comment]
@SheetJSDev  Thanks for your quick response. But that's not actually what I wanted. And also I'm not using AngularJS too. Here's simply what I need. It's great if you can find me a solution for this.

In your examples, I can see this code.
`var workbook = XLSX.readFile('test.xlsx');`
But you are saying we can use that only with NodeJS. So it's server side. Is there any way we can read a xls file in browser. You have added this code for browser use.
`var worksheet = XLSX.utils.table_to_book(document.getElementById('tableau'));`
Can we take a file from input field and make a worksheet from that using above code ?

Then I can simply use this following code and convert a worksheet to json.
`console.log(XLSX.utils.sheet_to_json(ws));`
It's so simple. No ?

Like this :+1: 

`var worksheet = XLSX.utils.table_to_book(document.getElementById('name_of_file_input'));
console.log(XLSX.utils.sheet_to_json(worksheet));`

Is there any way ? Please help me on this.

**Comment by SheetJSDev** [comment]
In https://github.com/sheetjs/js-xlsx#parsing-workbooks we gave some samples using AJAX in the browser and using the HTML5 file drag-and-drop.  You can't use `XLSX.readFile` in the browser because the browser exposes no way of just requesting data.  Use `XLSX.read` instead -- it accepts the data directly and supports binary strings (like those from `readAsBinaryString`) as well as base64 text and other data representations.

For example, in the http://oss.sheetjs.com/js-xlsx/ demo, https://github.com/SheetJS/js-xlsx/blob/gh-pages/index.html#L209 handles the file drop. For readAsBinaryString, you get the data and call `XLSX.read(data, {type:"binary"})`.

To read from an input element, jump down to "HTML5 input file element using readAsBinaryString or readAsArrayBuffer" example.
