### ISSUE TITLE
Background color not displayed

### ISSUE THREAD

**Issue by hawasthi02** [SheetJS/js-xlsx#639]
I am unable to see background in xlsm file.

I have imported these libraries
xlsx = require('xlsx'),
fileSaver = require('file-saver');

I am using the following code

for setting the background
cell = {t:'n' , v: workSheet['A' + (row+1)].v + workSheet['B' + (row+1)].v , f:'A' + (row+1)+'+'+'B'+(row+1) ,s: {bgColor: { indexed: 64 }}};

and this for writing into file
wbout = xlsx.write(wb, {bookType:'xlsx', bookSST:true, type: 'base64',cellStyles:'true'});

// to blob
function sheet_to_blob (s) {
const buf = new ArrayBuffer(s.length)
const view = new Uint8Array(buf)
for ( var i = 0; i != s.length; ++i ) view[i] = s.charCodeAt(i) & 0xFF
return buf
}
// export xlsx with file-saver
fileSaver.saveAs(new Blob([sheet_to_blob(wbout)], {
type: 'application/octet-stream'
}), 'test.xlsx')

and it says ReferenceError: Blob is not defined

**Comment by hawasthi02** [comment]
@SheetJSDev  Please help me with solution...

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
