### ISSUE TITLE
Any solution for styling cells of the excel?

### ISSUE THREAD

**Issue by Harsangeet** [SheetJS/js-xlsx#662]
I tried to style the current cell using

` s: { font: { sz: "11", bold: true }}`

But the cells are not getting styles. Any other approach?

**Comment by LizanLycan** [comment]
Same problem. Any solution?

**Comment by Harsangeet** [comment]
Hi Lizan,

I used xslx-style and styled the excel.

https://www.npmjs.com/package/xlsx-style.


Harsangeet

**Comment by LizanLycan** [comment]
Hi, I decided to use xlsx-populate because the one you mention does not work either

**Comment by Harsangeet** [comment]
Okay, but i am using xlsx-style in my app and able to format cells.
Thanks for one more alternative, always good to have options .

Harsangeet

**Comment by pumpkinp** [comment]
6666666666

**Comment by FinesseRus** [comment]
Try [exceljs](https://github.com/guyonroche/exceljs)

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by DineshThangella** [comment]
@Harsangeet  Can I have the code sample how to apply bold using xlsx-style
