### ISSUE TITLE
Proposal: convert the current code base to TypeScript

### ISSUE THREAD

**Issue by e-cloud** [SheetJS/js-xlsx#668]
Modern-version JavaScript allows more possibilities to ensure better robustness of the code base. It can also be analyzed by external tools to make some optimization and find out some performance bottleneck. Code refactoring is much more easy in Typescript.

I know js-xlsx has some flow types commented in the source code. But i think that is not enough. I've been spending the fragmented time of the past few weeks to convert the code base of js-xlsx to Typescript-based.

Happy to announce, the whole job is almost done. Some bugs are found. A lot of unused codes. Some codes are with problem. Most of types(with empty declaration) need complementation. Nevertheless, the compiled code passes most of the tests except a few bug related to timezone(#663) as i thought.

And Typescript supports transpiling codes into ES5 or even ES3(I haven't try this).

I need confirmation from @SheetJSDev to carry on this conversion.

**Comment by SheetJSDev** [comment]
@e-cloud glad to hear you were interested and I wish you reached out sooner!

We recently integrated the types from DefinitelyTyped into the repo (PR https://github.com/SheetJS/js-xlsx/pull/655) so if you've come across any improvements to the definitions we'd love to include them.

Now as for the long-term strategy, the main advantage of sticking to JS with flow comments is that the final result after minification is unchanged: since flow comments are comments, they are stripped.  There are lots of funny bugs with JS engines that require more fine-grained control.

For example, we recently stumbled across an issue with Adobe Photoshop that basically boiled down to a semicolon problem (see https://github.com/mishoo/UglifyJS2/issues/1930) -- and to resolve that issue, we ended up reintroducing the semicolon in our own forked version of the minifier (https://www.npmjs.com/package/@sheetjs/uglify-js):

```js
switch(x){case 1:break;default:break}
//----------------------------------^ ERROR: semicolon must appear after the break and before the end brace
switch(x){case 1:break;default:break;}
//----------------------------------^ OK
```

So at some level, for maximal compatibility we need as much control as possible over the final product.  Adding an additional layer like typescript introduces another potential layer of issues.  For that reason we're better off sticking with pure JS.  Flow is "free" insofar as the comments themselves do not affect the resulting code, and there is no compilation step required to use the type-annotated code.

As for your effort, if you came across any bugs or weaknesses in the code, we'd definitely like to take a look!

P.S.: I really think TS would benefit from inline comments

**Comment by e-cloud** [comment]
That's really a pity!

IMO, the semicolon issue is just related to uglify-js; With my few experience, the output of Typescript is as solid as babel.

You may have your concern. But the branch repo will continue and it may evolve independently with synchronization. One day, it may worth revisiting. :smile:
