### ISSUE TITLE
Link to other sheets with wrong text encoding

### ISSUE THREAD

**Issue by futurist** [SheetJS/js-xlsx#684]
I have a demo file with Chinese sheet names, when link to each other, the `cell.l` object have wrong text encoding as below:

```
cell.l.Target == "å·¥ä½è¡¨2!A1"
```

Which should be:

```
cell.l.Target == "工作表2!A1"
```

The demo excel is below:

[link-broken.xlsx](https://github.com/SheetJS/js-xlsx/files/1070034/link-broken.xlsx)

**Comment by SheetJSDev** [comment]
If you have a few minutes, the fix is super simple!  The [actual read](https://github.com/SheetJS/js-xlsx/blob/master/bits/67_wsxml.js#L111) should be wrapped in `utf8read`:

```diff
-		var val = parsexmltag(data[i], true);
+		var val = parsexmltag(utf8read(data[i]), true);
```

This is similar to what we do with [sheet names](https://github.com/SheetJS/js-xlsx/blob/master/bits/72_wbxml.js#L62):

```js
				y.name = unescapexml(utf8read(y.name));
```

We'd accept a PR with that change :)

**Comment by futurist** [comment]
I've tried, this fix did solve the problem, thank you!

Please see the PR

**Comment by SheetJSDev** [comment]
Thanks a lot! It will show up in the next release.
