### ISSUE TITLE
Working with pivot tables

### ISSUE THREAD

**Issue by Shrpt** [SheetJS/js-xlsx#71]
This and the XLS libraries have been lifesavers!  I can only imagine the blood, sweat and tears that went into this. 

I want to be able to see the pivot tables in a workbook. Is that possible?  I didn't see any options for it.

**Comment by azukaar** [comment]
+1 For this feature, at least would there be a workarround to be able to work with a workbook without loosing the existing pivot Table ?

**Comment by makanaki** [comment]
+1 this is the only feature stopping me from moving to JS

**Comment by willemmulder** [comment]
Is there any update on this? This would be great to have!

**Comment by kurt343** [comment]
+1 for pivot table read/write support.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
