### ISSUE TITLE
Support full unicode

### ISSUE THREAD

**Issue by uzulla-san** [SheetJS/js-xlsx#72]
Some unicode characters are not saved when writing the file

**Comment by notatestuser** [comment]
So to bump this one I just had to investigate an issue where emojis were being written to the SST and breaking MS Excel (but LibreOffice was okay with it).

The characters in question were just fairly standard emojis that were input on the iOS keyboard. e.g. 😉💚

In the SST these were not encoded and produced the fairly standard Excel panic in its repair output.
```xml
<removedParts summary="Following is a list of removed parts:"><removedPart>Removed Part: /xl/sharedStrings.xml part.  (Strings)</removedPart></removedParts>
```
Unfortunately this actually meant that it had removed the entire file so there were no strings in the visible spreadsheet at all.

I managed to repair the file manually by replacing the characters with their hex entity counterparts. For the emojis above these were `&#x1f609;` and `&#x1f49a;` respectively. Then when zipped back up the file opened and rendered the emojis all nicely:

![](https://cloud.githubusercontent.com/assets/1255926/6058920/5a7dfa0e-ad2c-11e4-8711-6928c188bf76.png)

I'm not sure the ideal solution would be to expand the table of [encodings](https://github.com/SheetJS/js-xlsx/blob/d4999ac4217d568bd700c641038f4034db2b0f63/bits/22_xmlutils.js#L23-29) with all possible unicode characters but would programatically generating the entity codes be a viable solution?

**Comment by SheetJSDev** [comment]
@notatestuser Can you check if putting `_x1f609_` works (instead of `&#x1f609;`)?  If so, then we should be able to simply change the regex that controls what characters are replaced (currently `/[\u0000-\u0008\u000b-\u001f]/g`)

**Comment by notatestuser** [comment]
As text? No that doesn't appear to work. See below:

![](https://cloud.githubusercontent.com/assets/1255926/6063304/722e3d92-ad56-11e4-8692-7bd6d29b35a3.png)

**Comment by notatestuser** [comment]
It may be possible to use a [surrogate pair](https://mathiasbynens.be/notes/javascript-encoding#surrogate-formulae) but the replacement logic will have to become more funky to do the split. I'll try that out and get back to you.

**Comment by notatestuser** [comment]
Okay I can confirm that using a surrogate pair with the `_` notation works: `_xd83d__xde09_` produces the emoji.

**Comment by SheetJSDev** [comment]
Oddly, Excel 2011 actually writes the UTF8 characters.  I inserted the same emoji character into a file and took a peek:

```
$ unzip -p test.xlsx xl/sharedStrings.xml | xxd
0000000: 3c3f 786d 6c20 7665 7273 696f 6e3d 2231  <?xml version="1
0000010: 2e30 2220 656e 636f 6469 6e67 3d22 5554  .0" encoding="UT
0000020: 462d 3822 2073 7461 6e64 616c 6f6e 653d  F-8" standalone=
0000030: 2279 6573 223f 3e0d 0a3c 7373 7420 786d  "yes"?>..<sst xm
0000040: 6c6e 733d 2268 7474 703a 2f2f 7363 6865  lns="http://sche
0000050: 6d61 732e 6f70 656e 786d 6c66 6f72 6d61  mas.openxmlforma
0000060: 7473 2e6f 7267 2f73 7072 6561 6473 6865  ts.org/spreadshe
0000070: 6574 6d6c 2f32 3030 362f 6d61 696e 2220  etml/2006/main"
0000080: 636f 756e 743d 2231 2220 756e 6971 7565  count="1" unique
0000090: 436f 756e 743d 2231 223e 3c73 693e 3c74  Count="1"><si><t
00000a0: 3ef0 9f8c 833c 2f74 3e3c 2f73 693e 3c2f  >....</t></si></
00000b0: 7373 743e                                sst>
```

According to section 22.9.2.19 ST_Xstring (Escaped String):

> For all characters which cannot be represented in XML as defined by the XML 1.0 specification, the characters are escaped using the Unicode numerical character representation escape character format _xHHHH_, where H represents a hexadecimal character in the character's value. 

Out of curiosity, what version of Excel was breaking?  I wonder if this behavior changed ...

**Comment by notatestuser** [comment]
I use Excel for Mac 2011 and it does the same thing.

But if you write out that character with js-xlsx you will notice that there's a difference in the way the characters are encoded. This is because JS strings are, for most intents and purposes, fixed length UCS-2 and not UTF-16 so a code point like `0x1f609` must is written out as two 16-bit characters.

Try `$ node -pe "'😉'.length"` to see the full strangeness of this.. JS actually represents it as two characters.

So the issue here is that JS doesn't just write out the UTF-16 character to the buffer because it can't. It encodes the character as two *surrogate halves* and expects the renderer to know how to recombine them back into a single character.

The full article [here](https://mathiasbynens.be/notes/javascript-encoding) is worth a read. Mathias gave an interesting talk about this at Fluent last year and the guy knows his Unicode.

**Comment by SheetJSDev** [comment]
I know there is no conversion from JS string to UTF8, but I can't get Excel 2011 to fail on this.

Can you try this: create a file with an offending character, save it as bad.xlsx, then run:

```
$ xlsx bad.xlsx
$ xlsx -X bad.xlsx -o nosst.xlsx
$ xlsx -X bad.xlsx --sst -o sst.xlsx
```

I just did this using the emoji winking face, and saw that the first correctly shows the character in iTerm2.  Can you confirm that you see the correct character in the console?  Also can you check both files (`open -a Microsoft\ Excel.app nosst.xlsx` etc).  I just tried that and both files show the correct unicode characters.

I stored my file and the outputs from xlsx 0.7.12 at http://sheetjs.com/dev/xlsx-72/ so you can also take a look

**Comment by notatestuser** [comment]
I'm unable to produce a bad file using that method. It's probably because the character is originating from Excel itself and not from some API call in JS. 

Today I got another broken file and the cause is another emoji. I recorded my prodding around:
```js
> emoji.charCodeAt(0).toString(16)
'd83d'
> var s = ''; var pos = x.indexOf(emoji); for (var i=pos-5; i<pos+5; i++){ s += x[i]; }; s
'dez) 😊</t'
> conv(s, {in:'utf8', out:'hex'})
'64657a2920f09f988a3c2f74'
> conv('f09f988a', {in:'hex',out:'utf8'})
'😊'
```

In vim these characters show as `<d83d><de0a>` in the SST. The file was produced by js-xlsx 0.7.11.

This emoji is `0x1f60a` so applying our surrogate pair conversion formula we get:
```js
> C = 0x1f60a
> H = Math.floor((C - 0x10000) / 0x400) + 0xD800
> L = (C - 0x10000) % 0x400 + 0xDC00
> H.toString(16)
'd83d'
> L.toString(16)
'de0a'
```

Removing these two characters fixed the file for Excel for Mac 2011.

**Comment by notatestuser** [comment]
I think we could just expand the [replacement regex](https://github.com/SheetJS/js-xlsx/blob/909e98d514cd956185b10061803732e33632fc30/bits/22_xmlutils.js#L39) to cover `0xd800..0xdbff` and `0xdc00..0xdfff` too which are the ranges for high and low surrogates.

Since Excel can render the recombined character when the surrogates are encoded with the `_` notation we'd be okay...

**Comment by notatestuser** [comment]
Here's my proposed solution for surrogate pair escaping. Just plonking it here for pre-PR comments.

```js
var decregex=/[&<>'"]/g,
    charegex = /[\u0000-\u0008\u000b-\u001f]/g,
    sprregex = /[\ud800-\udbff][\udc00-\udfff]/g;  // this is our SP replacement regex
function escapechr(chr) {
    return "_x" + ("000"+chr.toString(16)).substr(-4) + "_";
}
function escapexml(text){
	var s = text + '';
	return s
        .replace(decregex, function(y) { return rencoding[y]; })
        .replace(charegex, function(s) { return escapechr(s.charCodeAt(0)); })
        .replace(sprregex, function(s) { return escapechr(s.charCodeAt(0))+escapechr(s.charCodeAt(1)); });
}
```

**Comment by SheetJSDev** [comment]
@notatestuser The change looks just like what I had in mind.  Out of curiosity, could you send me a bad file so I can take a look?  I'm struggling to produce a file that will cause this problem

**Comment by notatestuser** [comment]
Sure, sent (dev@...)

**Comment by notatestuser** [comment]
Can confirm that the above code fixes my corruption issues.

**Comment by ibloat** [comment]
The _ syntax did not work for me in Libre Office.
Using numeric replacement seems to work though:

```js
var decregex=/[&<>'"]/g,
    charegex = /[\u0000-\u0008\u000b-\u001f]/g,
    sprregex = /[\ud800-\udbff][\udc00-\udfff]/g;  // <- SP replacement regex
function escapechr(chr) {
    return "_x" + ("000"+chr.toString(16)).substr(-4) + "_";
}
function cpfromsurrogates(s) {
    var H = s.charCodeAt(0) - 0xd800;
    var L = s.charCodeAt(1) - 0xdc00;
    return '&#x' + (H*0x400 + L + 0x10000).toString(16) + ';';
}
function escapexml(text){
    var s = text + '';
    return s
        .replace(decregex, function(y) { return rencoding[y]; })
        .replace(charegex, function(s) { return escapechr(s.charCodeAt(0)); })
        .replace(sprregex, cpfromsurrogates);
}
```
