### ISSUE TITLE
node/typescript not working together

### ISSUE THREAD

**Issue by shaunc** [SheetJS/js-xlsx#724]
I just installed this package using typescript (2.4.1) and node (7.10.0). I get the error:
```
node_modules/xlsx/types/index.d.ts(624,26): error TS2304: Cannot find name 'HTMLTableElement'.
node_modules/xlsx/types/index.d.ts(625,25): error TS2304: Cannot find name 'HTMLTableElement'.
```
I presume this is because `HTMLTableElement` is a dom construct which is not available in node.

**Comment by SheetJSDev** [comment]
@shaunc good catch! looking back, the [lint config](https://github.com/SheetJS/js-xlsx/blob/master/types/tsconfig.json#L4) specifies the DOM library, but that's clearly problematic.  Short-term the fix is to just make those `any` types (we can accept a PR that makes the change in https://github.com/SheetJS/js-xlsx/blob/master/types/index.d.ts#L624-L625 )
