### ISSUE TITLE
Is there any way that i can set background color when exporting json to xlsx

### ISSUE THREAD

**Issue by barneyliu708** [SheetJS/js-xlsx#727]
I am trying to export an json object to xlsx using XLSX.write(). I can set the data type and format as well as column width in the excel. However i cannot find a way to set the background color for my header row in the excel. 
here is my code to set background color but it does not work:
cell.s = { fill: { bgColor: { rgb: "ff6600" }  }  };

**Comment by sudhirt4** [comment]
Looking for similar feature 👍

**Comment by ggHamburg** [comment]
Hi, 
it seemed to be that you have to set fgColor. For me 
cell.s = { fill: { fgColor: { rgb: "ff6600" } } };
worked.

**Comment by Suncatcher** [comment]
@ggHamburg 

> cell.s = { fill: { fgColor: { rgb: "ff6600" } } };

For me it doesn't work. You used this library or xlsx-style?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
