### ISSUE TITLE
Is there a way to center all text in my worksheet?

### ISSUE THREAD

**Issue by jamespan0** [SheetJS/js-xlsx#729]
I am using xlsx through node-xlsx and I was wondering if I can style my entire document to have text-align:center

**Comment by Suncatcher** [comment]
Bump!

**Comment by HachimDev** [comment]
yes me too. That would be awesome !

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
