### ISSUE TITLE
readFile Strips Out Conditional Formatting

### ISSUE THREAD

**Issue by cklog** [SheetJS/js-xlsx#737]
Hello. Many, many thanks for your hard work on this library.

I have a workbook with two sheets, one that contains a few columns of validation data, and sheet another for inputting new data. Some columns on the latter sheet have conditional formatting, and use the validation data sheet to validate new inputs.

When I use XLSX.readFile(myWorkbook), the parsed file doesn't appear to contain conditional formatting data. I wanted to dynamically write in the validation data and save the workbook, but after reading the workbook, the conditional formatting is gone.

Thanks again.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
