### ISSUE TITLE
How to fill color for a cell?

### ISSUE THREAD

**Issue by vuongngolg** [SheetJS/js-xlsx#761]
I want to fill a color for a cell or a range, does xlsx support? Give me an example if have. 
Thanks! I am using this library to get data, so dont want to use another one to fill color. Please help.

**Comment by saptarshi007** [comment]
@SheetJSDev 
Do we have the solution for this?

**Comment by chinthu** [comment]
Its better to get a solution for this.. tried xlsx-style, but there are issues with its npm package

**Comment by hauteville86** [comment]
var excelCell = {
   v: valueOfColumn,
   t: "s",
   s: {
      fill: { fgColor: { rgb: "FFFFAA00"} } //here you can define the color you want to use
   }
};

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
