### ISSUE TITLE
How to distinguish a cell have underline

### ISSUE THREAD

**Issue by 253936563** [SheetJS/js-xlsx#763]
When cellData ifnt == 32, can i sure this cell have underline?Or other properties?

**Comment by SheetJSDev** [comment]
The `ifnt` refers to the index in the font table -- you need to inspect that table to determine the underline style.

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
