### ISSUE TITLE
Check if cell has fill color

### ISSUE THREAD

**Issue by Joselz** [SheetJS/js-xlsx#767]
Hello! I have seen some information about reading the color and style of the cells but in my case **i only need to check if the cell has any fill color or not**, and as a beginner, the discussions that I read did not seem very conclusive. Has there been any progress in this subject matter that could be useful for me?
Thanks!

**EDIT:** I dont know if this information is useful but I am using sheet_to_json to get the data from the Excel file.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
