### ISSUE TITLE
CDATA in cell values in XLSX format

### ISSUE THREAD

**Issue by awb99** [SheetJS/js-xlsx#775]
I have a strange problem with js-xlsx: 

I have XLSX files, and sometimes, when parsing them, all
string fields are internally comosed of CDATA strings. This tends to happen when I move
files form Windows to Linux or vice versa.  

This does NOT happen in xls files

This is an example:

```
{t: "s", v: "<![CDATA[Team Vienna]]>", w: "<![CDATA[Team Vienna]]>"}

```

The XLSX files can be read without a problem with Libreoffice.
Any ideas?

Regards
Andreas

**Comment by awb99** [comment]
http://oss.sheetjs.com/

I can replicate the bug also on this page.  All strings seem to be changed to the CDATA representation.

**Comment by awb99** [comment]
I fixed it with a string library. But I still dont get it why it occurs
```
var xmldecode = require('xmldecode');
 var cell_ref = XLSX.utils.encode_cell({ c: col, r: row });
    var desired_cell = ws[cell_ref];
    var desired_value = desired_cell.v;
    if (typeof desired_value == "string") {
        desired_value = xmldecode (desired_value);
   }

```

**Comment by SheetJSDev** [comment]
@awb99 thanks for the report!

XLSX files are really ZIP containers with XML files.  The strings in the workbook are usually stored in an XML file `xl/sharedStrings.xml` within the XLSX file.  Most writers follow the ECMA-376 spec, which has its own style of encoding special characters (_x0010_).  You stumbled upon a file which opted for the CDATA section logic.  The parser doesn't understand CDATA blocks, so it just dumps the entire string.

This doesn't show up in XLS because the representation is completely different.  There, the data is stored in binary records and the strings are usually stored in length-prefixed UTF-16 or codepage strings, avoiding the XML issue entirely.

We'll push a fix in the next version.
