### ISSUE TITLE
Older versions not coming up on NPMJS registry

### ISSUE THREAD

**Issue by deathgaze** [SheetJS/js-xlsx#778]
When I try to install older versions of this module, I get file not found errors from NPM.

The following url should have the older version 0.8.1, for example: https://registry.npmjs.org/xlsx/-/xlsx-0.8.1.tgz

however I get back json: 
```

{"error":"package could not be found."}

```

**Comment by SheetJSDev** [comment]
@deathgaze most of the older versions didn't pin dependency version numbers in package.json, causing problems in NPM 5.  See https://github.com/npm/npm/issues/17227 -- you should use a version after 0.9.2.

If you are using node, there was no breaking change since 0.8.  The major version jumped because of some browser-related interface issues (for example, there used to be a separate ods.js script, but that was causing issues with webpack so it was ultimately folded into the main xlsx.js and that triggered a version jump)
