### ISSUE TITLE
how to set Password when writeFile ?

### ISSUE THREAD

**Issue by parkAlly** [SheetJS/js-xlsx#791]
I want to set password when writeFile.
Do you support that feature?

```javascript
var wb , ws = {}; 
ws['!protect'] = false;
wb.Sheets['test'] = ws;
XLSX.writeFile(wb, 'xlsxFile', {password : 'test1234'});
```

**Comment by SheetJSDev** [comment]
A quick note on the feature: XLSX / XLSB ("ECMA-376") encryption involves generating a normal file and packaging the whole thing in an encrypted blob within a CFB container (the same type of container used in XLS).

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
