### ISSUE TITLE
how can I set the height for an specific cell? 

### ISSUE THREAD

**Issue by jorbope** [SheetJS/js-xlsx#793]
how can I set the height for an specific cell? for example A1
when I set to that cell a lot of text, I want to see the whole text when I open the xlsx, but currently I have to open the xlsx and resize manually the cell to see the whole text.

**Comment by appbeijing** [comment]
I meet the same problem,how to do ?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
