### ISSUE TITLE
XLSX.write fails to convert dates from iso-date format to excel date for xlsx output

### ISSUE THREAD

**Issue by EBMike** [SheetJS/js-xlsx#832]
This was broken between versions 0.10.3 and 0.10.4

Here is [a working fiddle from 0.10.3](https://jsfiddle.net/m4g3cehg/)
Here is [a failing fiddle from 0.10.4](https://jsfiddle.net/mmuobsay/)

...note that this worked AT LEAST from 0.8.8 up to 0.10.3 and is broken since.
an example iso-date used in fiddle is: "2017-10-04"

verion 0.10.3 and below will properly convert this to 10/4/2017
whereas, version 0.10.4 bugs out and produces 10/3/2017

**Comment by EBMike** [comment]
It appears the offending code is this...
![image](https://user-images.githubusercontent.com/15325216/31298244-46a27bb4-aab7-11e7-9862-57f02b8d6c45.png)

**Comment by SheetJSDev** [comment]
The behavior was changed to be consistent with Excel.  If you are adding dates to the worksheet object, you need to present the times as if they are the correct values in the timezone of the JS engine that is writing the file (not in UTC).  The readers and writers automatically perform the shift.  If you are passing in a string, since JS Date parsing defaults to UTC interpretation, you unfortunately have to manually shift it by passing a Date object.

Long story short: Excel actually has no native concept of timezones.  Every date value is converted back to a numeric code in the locale of the computer system.  This means when you type in a datetime in Excel like "10/4/17 00:00:00" and change your computer regional settings, you get back the same exact string!  This is really confusing coming from JS which does have a sense of timezones.  The original implementation did not address the inconsistency, and in fact running the test suite from a timezone which is ahead of UTC (e.g. `Asia/Kolkata`) would reveal the errors.

The reader "corrects" the discrepancy by shifting the date codes so that they appear correct to the local timezone.  When you save a file with the datetime `2017-10-04 00:00:00`, the value that you will see in the JS code will be that time in your current timezone (so you will see `2017-10-04T04:00:00.000Z` from New York, which is `2017-10-04 00:00:00` local time).

The writer "corrects" the discrepancy by shifting the dates back.  From the string representation, `"2017-10-04"` is interpreted as `2017-10-04T00:00:00.000Z` (midnight UTC) which is really `2017-10-03 20:00:00.000` in Eastern Time or `2017-10-03 17:00:00.000` Pacific Time.

**Comment by pmalouin** [comment]
I have some similar problems with the `datenum` function, not behaving correctly when the `v` is not in the same timezone offset as the current time (in a timezone where DST occurs). After playing around with the code, I believe the offsetting needs to be dependent on the `v` value instead of current time, like this:
```
var basedate = new Date(1899, 11, 30, 0, 0, 0);
var basetimestamp = basedate.getTime();
var baseoffset = basedate.getTimezoneOffset();
function datenum(v/*:Date*/, date1904/*:?boolean*/)/*:number*/ {
	var epoch = v.getTime();
	if(date1904) epoch -= 1462*24*60*60*1000;
	// Account for offset differences between the basedate and v...
	var adj = (v.getTimezoneOffset() - baseoffset) * 60000;
	return (epoch - basetimestamp - adj) / (24 * 60 * 60 * 1000);
}
```
This is because if `basedate` and `v` have a different offset, we need to compensate this effect by applying the difference on the numerical value provided to excel. The offset of the current time does not seem relevant.

It's possible that the `numdate` function suffers from the same problem, but I haven't digged through it.

**Comment by EBMike** [comment]
You may need to open a new issue, I don't think they are going to change it back to the way it was. I get why they did what they did, but its makes using iso-dates 10x harder. @pmalouin @SheetJSDev
