### ISSUE TITLE
How to export  the bootstrap the fonts icon

### ISSUE THREAD

**Issue by geminiyu233** [SheetJS/js-xlsx#834]

**Comment by SheetJSDev** [comment]
Just a quick note: You can actually install the FontAwesome (bootstrap font) TTF and reference it from Excel using the correct unicode values.

We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
