### ISSUE TITLE
Format spreadsheet as Table

### ISSUE THREAD

**Issue by bretthirst** [SheetJS/js-xlsx#838]
I am using the json_to_sheet utility function to convert my JS objects to a spreadsheet. Currently I am manually opening the spreadsheet and formatting it as table. Is it possible to automate this process with the json_to_sheet utility function or any other functions within SheetJS?

**Comment by chadkirby** [comment]
+1

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
