### ISSUE TITLE
 Does cell style support now? 

### ISSUE THREAD

**Issue by scholar-ink** [SheetJS/js-xlsx#844]
Does cell style support now?  
 The difference between xlsx-style and xlsx is too big

**Comment by kayakyakr** [comment]
The SheetJS website seems to indicate that it's hidden behind the prowall. Unfortunately, it doesn't seem like there's anyone regularly listening at the sheetjs support/payment email.

**Comment by derrohrbach** [comment]
The difference is ever growing. We really need to know if, when and how the support of styling is supposed to happen. Or if it really exists behind a paywall, we need better information about pricing, features and availability.

**Comment by YMC-GitHub** [comment]
Thank you for your contribution.And Does cell style support now?

**Comment by chuanpengli** [comment]
https://github.com/YMC-GitHub

**Comment by chuanpengli** [comment]
I had the problem too, and I get the answer.You should send an email to get the pro version and you probably get what you want but with some cost.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
