### ISSUE TITLE
Importing without row- or colspan

### ISSUE THREAD

**Issue by A-Dummy** [SheetJS/js-xlsx#868]
Is there an option to upload an excel file and parsing it into an HTML-table, but ignoring row- and colspans?

**Comment by reviewher** [comment]
No because of how HTML works.  Here's an example with A1:B2 merged:

```html
<table border=1>
  <tr>
    <td colspan="2" rowspan="2">A1:B2</td>
    <td>C1</td>
  </tr>
  <tr><td>C2</td></tr>
  <tr>
    <td>A3</td>
    <td>B3</td>
    <td>C3</td>
  </tr>
</table>
```

<table border=1>
<tr>
<td colspan="2" rowspan="2">A1:B2</td>
<td>C1</td>
</tr>
<tr><td>C2</td></tr>
<tr><td>A3</td><td>B3</td><td>C3</td></tr>
</table>

Notice how the second row has only one element but it is in the third column -- that's specified in the rowspan and colspan properties
