### ISSUE TITLE
formatting excel sheets

### ISSUE THREAD

**Issue by bolemeus** [SheetJS/js-xlsx#87]
I've been struggling to format individual cells within a worksheet.
I want to increase the font size of certain cells, and make header cells bold.

I'm also trying to increase the width of columns, so that the contents fit.

Sofar I'm passing something like to following to XLSX.write() function.

{
  "A1": {
    "t": "s",
    "v": "Rapport per periode"
  },
  "A3": {
    "t": "s",
    "v": "Datum verwerkt vanaf"
  },
  "B3": {
    "t": "n",
    "v": 41818.916666667,
    "z": "m\/d\/yy"
  },
  "A4": {
    "t": "s",
    "v": "Datum verwerkt t\/m"
  },
  "B4": {
    "t": "n",
    "v": 41852.916666667,
    "z": "m\/d\/yy"
  },
  "!ref": "A1:F17"
}

This works fine, but I'm struggling to discover more formatting options.

Am I missing some documentation? Or is this not yet possible?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
