### ISSUE TITLE
Add missing jszip to package.json

### ISSUE THREAD

**Issue by renatobenks** [SheetJS/js-xlsx#873]
Hey guys, to solve the problem about `jszip it's not a constructor` on importing `xlsx`, the `jszip` should be in `package.json`. I just wanna know, why don't? Pls, let me know if this is relevant, because I solved this issue like that and I have my fork ready for send PR, adding the missing lib to `xlsx` npm packages.

_Obs.: this is going on with too much people._

**Comment by reviewher** [comment]
Check that you are using the latest version, since we changed the dist script configuration going into 0.11.0.

For straight script tag insertion in a web page, use [`dist/xlsx.full.min.js`](https://unpkg.com/xlsx/dist/xlsx.full.min.js) instead of the individual scripts.

In NPM, `require('xlsx')` should just work, as it's how the [`xlsx` CLI tool](https://github.com/SheetJS/js-xlsx/blob/master/bin/xlsx.njs) invokes the library.

Without seeing a project structure, it's hard to say what's going on, but there are various [demos](https://github.com/SheetJS/js-xlsx/tree/master/demos) showing projects using angular, react, electron, and other frameworks.

**Comment by renatobenks** [comment]
@reviewher I'm using the latest version!
