### ISSUE TITLE
Styling the Cell was included in the latest package.

### ISSUE THREAD

**Issue by dstvishnu** [SheetJS/js-xlsx#889]
Whether the changes to add the styles to the content while writing the .xlsx format was included in the package?.If yes then how to use styling?

**Comment by sathish804** [comment]
I don't think its included in the latest release.

You can refer to the below fork link for using styling with .xlsx file.

https://github.com/protobi/js-xlsx

**Comment by Mic1** [comment]
I started at protobi/js-xlsx and worked my way up to community SheetJS where I have the imported workbook containing the styles object for a cell and empty cells showing .... but the empty cells do not include the styles object. Followed a link where the problem can be apparently solved by a mod to the safe_format function ..... which does not work as this function not getting called. Am using the SheetJS Live Grid Demo to test this. Has anyone got the empty cells to include their style object?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
