### ISSUE TITLE
read a xlsx template then change its content

### ISSUE THREAD

**Issue by zhouseahe** [SheetJS/js-xlsx#89]
I want to read a xlsx template then change its content , 
Do this support it ?  thanks .

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by optimistex** [comment]
I implement xlsx template engine: https://github.com/optimistex/xlsx-template-ex
It bases on exceljs. Try it. May be it will be useful for you!?
