### ISSUE TITLE
how to use xlxs export emage to excel? i use it ,but not  available

### ISSUE THREAD

**Issue by zoe-cjf** [SheetJS/js-xlsx#919]
this is the code ,what's wrong？？？？？？？
![image](https://user-images.githubusercontent.com/29645498/34024011-945aab60-e10d-11e7-8b8f-fc172ef74df2.png)

**Comment by zoe-cjf** [comment]
![image](https://user-images.githubusercontent.com/29645498/34024008-8e7b053c-e10d-11e7-8625-23d38f15c752.png)

**Comment by ismarf9** [comment]
@zoe-cjf nothing?

**Comment by rama10** [comment]
I have the same problem.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
