### ISSUE TITLE
Caching issue: Is it done by filename only for drop zone?

### ISSUE THREAD

**Issue by bean5** [SheetJS/js-xlsx#930]
**Expected**
Changing a file's hash forces alert upon opening file for second time.

**Actual**
Cached version of file appears instead of new file. No option to clear cache is automatically provided.

**Steps to Reprodcude**
* Open http://oss.sheetjs.com/
* Open a file using SheetJS using the drop zone.
* Delete a column, make other changes as desired
* In Excel, make other edits to the file (decide to use Excel for some operations)
* Open the file using SheetJS using the drop zone.

I am not sure whether the SheetJS core is doing this or if the demo is doing something strange. I have not seen the file picker do this, so I am thinking it is a drop zone bug. Since I am new to the project, I don't know where to debug to prove it is only a bug with how you use the drop zone.

**Comment by SheetJSDev** [comment]
This is a flaw of the browser input element, completely out of our control.  The `change` event for an HTML file input element is only fired if the filename changes.  If you try to submit a file with the same exact absolute path, the browser does not register a change, which is why the demo appears to cache data.  You can verify that the demo is not caching by:

- submit first file
- submit second file
- change first file
- resubmit first file

You can also try to drag and drop files into the box.  The event is always fired in that case.

P.S.: the code for oss.sheetjs.com is in https://github.com/SheetJS/SheetJS.github.io

**Comment by bean5** [comment]
Thank you for the prompt response. So there are no work-arounds for the issue?

**Comment by SheetJSDev** [comment]
I can think of one workaround: generate a new file input element and hide the previous one.  If you really need to push the same file again, I recommend using drag and drop (it will always fire).
