### ISSUE TITLE
Write some Style imformation to merged Cells

### ISSUE THREAD

**Issue by Robotics1** [SheetJS/js-xlsx#936]
Hey i am writing some merged cells to a file but i am not completly sure how to style them the style attribute just counts for the first cell.

I tried to read in examples and understand it that way but i cannot find a real solution how to do it

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
