### ISSUE TITLE
How to apply style in headings

### ISSUE THREAD

**Issue by ankita199** [SheetJS/js-xlsx#948]
I am trying to apply styling in heading of xlsx which i am generating from json. I R&D about it and found 'xlsx-style' module for styling but in that there is one issue of cpexcel file. So need to copy cpexcel form xlsx/dist to xlsx-style/dist. This is working in development but while production build i can't follow this steps.

Is any other was for styling 'xlsx' file ?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
