### ISSUE TITLE
Sorting issue when the length of the object holding the data coming from an API endpoint !!!

### ISSUE THREAD

**Issue by prajwal78** [SheetJS/js-xlsx#955]
I have an issue where the value for the date and time interval 
![image](https://user-images.githubusercontent.com/10049692/34987127-5f71052c-faba-11e7-97df-0bf05ec6932d.png) 
   is supposed to be placed between the other values for the other date and time intervals like shown in

![image](https://user-images.githubusercontent.com/10049692/34986713-e2f1ac64-fab8-11e7-9d97-4671ca87644f.png).
    
     But, the value is place the bottom of the column like seen in the image

![image](https://user-images.githubusercontent.com/10049692/34986772-2060505a-fab9-11e7-86ad-f48cb1d52935.png)

Is this the package issue or some kind of custom logic needs to be in place to prevent the sorting issue? Any sort of help will be appreciated.

**Comment by reviewher** [comment]
Is this happening when you are reading or writing files?  Can you share a small test so we can reproduce?

**Comment by prajwal78** [comment]
It is happening while writing the data into Excel. I can't provide a small test app or something is the functionality of huge React based application. I have provided the information the most I could as described below:

This is the data in JSON format coming from the API endpoint [data.txt](https://github.com/SheetJS/js-xlsx/files/1638829/data.txt). Sorry, the editor doesn't support Javascript file formats. So, I put it in .txt format. One thing to notice in the data is that 'data' property in 'test 1' object has 196 items whereas 'data' property in 'test 2' and 'test 3' has 197 items in each. I have also read that if there is some empty data, then excel has sorting issues.

This is the snippet of code generating excel sheet for me: 
![image](https://user-images.githubusercontent.com/10049692/35042284-4c003b7e-fb88-11e7-8323-dc27bb2ae4fa.png)

This is the excel file generated coming from the data from the API endpoint [PrajwalExcel.xlsx](https://github.com/SheetJS/js-xlsx/files/1638820/PrajwalExcel.xlsx)

I hope this might help a bit to figure out the issue.

**Comment by SheetJSDev** [comment]
The actual XLSX file shows the same inversion.  Since the `json_to_sheet` function just loops the array in-order, this is an issue with your `exportDataToExcel` function.  To verify this, add the line `console.log(data)` in `generateExcelSheet` and you should see that the array you are passing also has an inverted date.

In general `Object.keys` is not guaranteed to give you a sorted list of keys in ES5 (ES6+ has some guarantee).  You can either try to sort the array using a comparator that parses the dates or store the items in an array.

P.S.: since you aren't capturing the result, you should be using `forEach` rather than `map`
