### ISSUE TITLE
set row background?

### ISSUE THREAD

**Issue by FrostAway** [SheetJS/js-xlsx#967]
ws = {
...
A1: {t: 'n', v: 1, s: {fill: {bgColor: 'ff0000'}}}
}
not work,
how I see the docs?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
