### ISSUE TITLE
Corrupt xlsx file when converting from csv (or tsv) and exporting and downloading

### ISSUE THREAD

**Issue by RSpicer** [SheetJS/js-xlsx#973]
Hi there!

Here's my issue. I'm currently trying to import essentially a TSV file in text to js-xlsx with .read(), and then have it write out an xlsx file. I don't particularly care about export type (buffer, base64, binary) as long as it works. Unfortunately, my methods seem to always end in a corrupted file.

Here's my current code:
```

res.setHeader('content-type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
var parsedStream = totalStream.split(',').join('","'),
csvStream = parsedStream.split('\t').join(','),
wb = xlsx.read(csvStream, { type: "buffer" }),
outStream = xlsx.write(wb, { type: "buffer" });
res.send(200, outStream);
```

This is me converting my tsv to csv for the purposes of the read. TSV doesn't seem to work either. Keep in mind that I know for a fact that this TSV is valid, as we use the raw TSV data to export, well, TSV... and it works fine. Here's the other end:

```
      let options;
      if (values.fileType === 'xlsx') {
      	options = {responseType: 'arraybuffer', headers: {'TS-JWT': jwtlocal}}
      } else {
      	options = {headers: {'TS-JWT': jwtlocal}}
      }

      const res = await axios.post(`${uri}`, {}, options);

      console.log(res.data)

	  let types = {
			"xlsx": {
				"mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
				"extension": "-export.xlsx"
			},
			"tsv": {
				"mimeType": "text/tab-separated-values; charset=utf-8",
				"extension": "-export.tsv"
			}
		}
		let type = types[values.fileType]
		FileSaver.saveAs(new Blob([res.data], {type: type.mimeType}), values.survey + type.extension)
```

Any help would be greatly appreciated. I may just be missing an option specific to CSV/TSV text and their imports, but I didn't see anything. Cheers!

**Comment by SheetJSDev** [comment]
In the first code block: `csvStream` is a string based on usage so you need to [read with type `binary`](https://docs.sheetjs.com/#input-type):

```js
var parsedStream = totalStream.split(',').join('","'), // parsedStream is a string based on usage
	csvStream = parsedStream.split('\t').join(','), // csvStream is a string based on usage
	wb = xlsx.read(csvStream, { type: "binary" }), // wb is a workbook
	outStream = xlsx.write(wb, { type: "buffer" }); // outStream is a buffer based on usage
```

The second code block issue is outside the purview of the library, but most of the examples write using `type:"array"` and call `saveAs` with type `"application/octet-stream"`.

We have an axios demo in the [`xhr` demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr) if you want to see a sample use case.

**Comment by SheetJSDev** [comment]
In the first block, it looks like you are using `totalStream` as if its a string.  The `"buffer"` type operates as if you passed a `Buffer`, but since you're passing a string you should use `"binary"` or `"string"` depending on how you generated the string.

Here's a simple `http` server using `formidable` to parse the body.  It looks for the file uploaded to the `data` field of the form:

```js
const http = require('http');
const formidable = require('formidable');
const XLSX = require('xlsx');
const server = http.createServer((req, res) => {
	if(req.method !== 'POST') return res.end("Submit a POST request");
	const form = new formidable.IncomingForm();
	form.parse(req, function(err, fields, files) {
		const f = files.data;
		const wb = XLSX.readFile(f.path);
		res.end(XLSX.write(wb, {type:"buffer", bookType:"xlsx"}));
	});
}).listen(3000);
```

To test:

```bash
$ echo -e "a\tb\tc\n1\t2\t3" > t.tsv
$ curl -X POST -F "data=@t.tsv" http://localhost:3000/ > t.xlsx
```

The second code block issue is outside the purview of the library, but most of the examples write using `type:"array"` and call `saveAs` with type `"application/octet-stream"`.  To see where it's failing:

1) try dumping the file in the server:

```js
// ...
		const wb = XLSX.readFile(f.path);
		const out = XLSX.write(wb, {type:"buffer", bookType:"xlsx"});
		fs.writeFileSync("out.xlsx", out); // copy out.xlsx to your computer and verify
		res.end(out);
// ...
```

2) To check if the client is receiving the correct data, load the library on the client side and try to parse:

```js
// ...
const res = await axios.post(`${uri}`, {}, options);
console.log(XLSX.read(res.data, {type: "array"}));
// ...
```

If the first fails, its a library issue, and we would need to see `JSON.stringify(wb)` as well as a copy of the resulting file.  If the second is failing, that's a server - client issue, and it would be good to start by using cURL to make the request.  If both are valid but the generated file is bad, then it's a filesaver issue.

**Comment by RSpicer** [comment]
Thanks boss 👍
