### ISSUE TITLE
bug with font bold=true

### ISSUE THREAD

**Issue by AviAkGlobal** [SheetJS/js-xlsx#984]
Using bold <b> with xlsx file format doesn't create bold=true in the font object. Please review:
`function parse_fonts(t, styles, themes, opts)`

and add the following line:
```
case '<b': font.bold = y.val ? parsexmlbool(y.val) : 1; break;
**case '<b>':**
case '<b/>': font.bold = 1; break;
```

unless I'm mistaken...

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
