### ISSUE TITLE
Read and write Data validations

### ISSUE THREAD

**Issue by ShirishResilinc** [SheetJS/js-xlsx#990]
Hi All,
Is there any plan to add data validation feature while reading and writing the excel sheet?

**Comment by ismarf9** [comment]
@ShirishResilinc  if you can read, you can validate, be specific!

**Comment by ismarf9** [comment]
What do you want to do?

**Comment by ShirishResilinc** [comment]
Is there any plan to add above functionality in xlsx-js or is it available in pro version as from sheetjs.com it is   not clear whether pro version is having it or not.

**Comment by ismarf9** [comment]
@ShirishResilinc this is @SheetJSDev

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
